import { useCallback, useEffect, useRef, type RefObject } from "react";
import { useI18n, type LocaleCode } from "../i18n";
import { toTraditionalChinese } from "../i18n/messages/zh-TW";

const englishConfigCopy: Record<string, string> = {
  "提示音管理": "Sound management",
  "管理图片任务完成和失败时使用的全局提示音。仓库与发行包不包含音频文件。": "Manage the global sounds used when image tasks complete or fail. The repository and release packages do not include audio files.",
  "需要更多提示音？": "Need more sounds?",
  "可前往 Mixkit 手动下载，再上传到本地。使用前请自行确认素材许可。": "Download sounds manually from Mixkit, then upload them locally. Confirm the asset license before use.",
  "前往 Mixkit": "Open Mixkit",
  "前往 Mixkit 下载提示音": "Download sounds from Mixkit",
  "个提示音": "sounds",
  "音频保存在本地 data 目录，并随数据备份。": "Audio is stored in the local data directory and included in data backups.",
  "上传音频": "Upload audio",
  "提示音加载中...": "Loading sounds...",
  "暂未配置提示音": "No sounds configured",
  "从素材网站下载有权使用的音频后，在这里上传即可。": "Download audio you are authorized to use, then upload it here.",
  "格式/大小": "Format / size",
  "上传提示音": "Upload sound",
  "显示名称": "Display name",
  "仅支持 MP3、WAV、OGG，单文件不超过 5MB。请确认你拥有相应的使用权。": "Supports MP3, WAV, and OGG up to 5 MB. Confirm that you have the required rights.",
  "提示音已上传": "Sound uploaded",
  "提示音名称已更新": "Sound name updated",
  "提示音已启用": "Sound enabled",
  "提示音已停用": "Sound disabled",
  "提示音已删除": "Sound deleted",
  "修改提示音名称": "Rename sound",
  "删除提示音": "Delete sound",
  "安全审核": "Safety review",
  "安全审核配置保存失败": "Failed to save safety review settings",
  "安全审核配置已保存": "Safety review settings saved",
  "安全审核配置已自动保存": "Safety review settings auto-saved",
  "按调用方式": "By route",
  "按渠道": "By channel",
  "按渠道、调用方式和具体渠道查看请求质量。": "Review request quality by channel, route, and provider.",
  "按渠道聚合": "By channel",
  "按生成、编辑、用户、团队和渠道观察图片产出。": "Review image output by generation, edits, users, teams, and channels.",
  "按时间范围查看系统整体、用户团队、图片产出、渠道请求、图片账号和失败情况。": "Review system totals, users, teams, image output, channel requests, image accounts, and failures by date range.",
  "按顺序依次尝试 CPA、ChatGPT 官网和 API 直连渠道。": "Try CPA, ChatGPT Web, and direct API channels in order.",
  "按团队": "By team",
  "按用户": "By user",
  "按优先级": "By priority",
  "按账号聚合": "By account",
  "保存": "Save",
  "保存后会自动隐藏": "Hidden automatically after saving",
  "保存名称": "Save name",
  "保存配置": "Save settings",
  "保存渠道": "Save channel",
  "保存日志": "Save log",
  "保存账号": "Save account",
  "保存中": "Saving",
  "备份配置已自动保存": "Backup settings auto-saved",
  "备份配置自动保存失败": "Failed to auto-save backup settings",
  "备份任务已开始": "Backup started",
  "备份已删除": "Backup deleted",
  "备份运行数据库和图片素材文件；备份包包含敏感配置，请保存到可信目录。": "Back up the runtime database and image assets. Backup packages contain sensitive settings, so save them to a trusted directory.",
  "备份中": "Backing up",
  "本地": "Local",
  "本地成功排行": "Local success ranking",
  "本地兜底": "Local fallback",
  "本地请求排行": "Local request ranking",
  "本地失败排行": "Local failure ranking",
  "本地图像接口": "Local image API",
  "本月": "This month",
  "编辑": "Edit",
  "编辑账号": "Edit account",
  "标题生成": "Title generation",
  "标准额度": "Standard quota",
  "表单翻译": "Form translation",
  "表单优化": "Form optimization",
  "不绑定": "Not bound",
  "不绑定渠道": "No bound channel",
  "不可导入": "Cannot import",
  "不使用": "Do not use",
  "参与轮播": "Include in carousel",
  "测试短信已发送": "Test SMS sent",
  "测试邮件已发送": "Test email sent",
  "查看号池状态、本地调用排行和最近 CPA 同步结果。": "Review account pool status, local call rankings, and recent CPA sync results.",
  "查看用户活跃、团队产出和管理权限账号分布。": "Review user activity, team output, and admin permission distribution.",
  "成功": "Success",
  "成功率": "Success rate",
  "尺寸未知": "Unknown size",
  "处理中": "Processing",
  "错误信息已复制": "Error copied",
  "代理配置": "Proxy settings",
  "代理配置已保存": "Proxy settings saved",
  "待审核": "Pending review",
  "待同步": "Pending sync",
  "当前配置": "Current settings",
  "当前提示词可能存在安全风险，请调整后再试。": "The current prompt may contain safety risks. Adjust it and try again.",
  "导出网页": "Export web page",
  "导入中": "Importing",
  "等待中": "Waiting",
  "低": "Low",
  "点击查看完整提示词": "Click to view full prompt",
  "调试配置": "Debug settings",
  "调试配置已保存": "Debug settings saved",
  "定位高频错误、失败渠道和最近失败请求。": "Locate frequent errors, failing channels, and recent failed requests.",
  "独立维护 AI 优化提示词使用的 OpenAI Chat Completions 兼容语言模型，不复用图片渠道。": "Maintain the OpenAI Chat Completions-compatible model used for AI prompt optimization separately from image channels.",
  "概览": "Overview",
  "读取账号详情中": "Loading account details",
  "短信配置": "SMS settings",
  "短信配置已保存": "SMS settings saved",
  "对话标题": "Chat title",
  "对话标题自动生成失败": "Failed to generate chat title",
  "发送测试短信": "Send test SMS",
  "发送测试邮件": "Send test email",
  "发送中": "Sending",
  "复制失败": "Copy failed",
  "改为通过": "Approve",
  "改为通过灵感": "Approve inspiration",
  "改为通过素材共享": "Approve asset sharing",
  "改为未通过": "Reject",
  "改为未通过灵感": "Reject inspiration",
  "改为未通过素材": "Reject asset",
  "高": "High",
  "高频错误摘要": "Frequent error summaries",
  "更新": "Update",
  "更新日志": "Changelog",
  "更新日志已保存": "Changelog saved",
  "更新日志已删除": "Changelog deleted",
  "更新日志已新增": "Changelog added",
  "同步英文日志": "Sync English changelog content",
  "供应商测试失败": "Provider test failed",
  "关闭": "Close",
  "关闭调试保存": "Disable debug saving",
  "关闭管理权限": "Disable admin access",
  "关闭后，新加入灵感会直接公开；历史待审灵感仍保留当前状态。": "When disabled, new inspirations are published directly. Existing pending inspirations keep their current status.",
  "关闭后，新提交共享的素材会直接公开；历史待审素材仍保留当前状态。": "When disabled, newly shared assets are published directly. Existing pending assets keep their current status.",
  "官网额度 / Codex 额度": "Web quota / Codex quota",
  "官网模式": "Web mode",
  "官网优先": "Web first",
  "管理权限": "Admin access",
  "管理权限已更新": "Admin access updated",
  "记录": "Records",
  "记录配置入口的重要操作。": "Record important admin actions.",
  "记录语言模型调用的场景、供应商、状态、重试次数和接口地址；不保存请求正文和响应正文。": "Record language-model call scenario, provider, status, retry count, and endpoint. Request and response bodies are not saved.",
  "记录最近图片请求实际使用的渠道、调用方式、重试次数和接口地址。": "Record the actual channel, route, retry count, and endpoint used by recent image requests.",
  "接口 ID 不能为空": "Endpoint ID is required",
  "接口 ID 已存在": "Endpoint ID already exists",
  "结束日期": "End date",
  "今年": "This year",
  "今日": "Today",
  "今日图片数": "Images today",
  "今日实时图片": "Images today",
  "今日暂未生成文案。": "No copy has been generated today.",
  "今日文案已更新": "Today's copy updated",
  "近 1 年": "Last year",
  "近 30 天": "Last 30 days",
  "近 7 天": "Last 7 days",
  "禁用": "Disabled",
  "禁用用户": "Disabled users",
  "禁用账号": "Disable account",
  "拒绝": "Reject",
  "拒绝灵感公开": "Reject inspiration",
  "拒绝素材共享": "Reject asset sharing",
  "拒绝原因": "Rejection reason",
  "开关保存失败": "Failed to save switch",
  "开启": "Enable",
  "开启调试保存": "Enable debug saving",
  "开启管理权限": "Enable admin access",
  "开启后每天凌晨由启用的语言模型生成生图相关互动文案；关闭或失败时继续使用本地固定文案。": "When enabled, the active language model generates image-related starter copy every morning. When disabled or failed, local fixed copy remains in use.",
  "开始日期": "Start date",
  "可导入": "Can import",
  "可留空；保存后会脱敏显示": "Optional. Masked after saving.",
  "可选，手机号登录预留": "Optional. Reserved for phone login.",
  "可选，用于邮箱登录和找回密码": "Optional. Used for email login and password recovery.",
  "可用": "Available",
  "可用图片账号": "Available image accounts",
  "可粘贴完整授权 JSON，系统会尽量提取邮箱、类型和令牌": "Paste full auth JSON. The system will try to extract email, type, and token.",
  "空白页每日文案": "Daily blank-page copy",
  "空白页文案": "Blank-page copy",
  "控制图片生成整体从哪类渠道选路。": "Control which channel type image generation routes through.",
  "拦截": "Block",
  "例如 http://127.0.0.1:8317": "Example: http://127.0.0.1:8317",
  "例如 v0.1.1": "Example: v0.1.1",
  "灵感审核": "Inspiration review",
  "灵感审核状态": "Inspiration review status",
  "灵感已拒绝公开": "Inspiration rejected",
  "灵感已通过审核": "Inspiration approved",
  "流式": "Streaming",
  "留空不重试": "Leave empty for no retries",
  "留空使用模型默认值": "Leave empty to use the model default",
  "留空则复用注册模板": "Leave empty to reuse the registration template",
  "轮询": "Round robin",
  "每次随机挑选可用账号": "Randomly select an available account each time",
  "每日文案": "Daily copy",
  "每日文案更新失败": "Failed to update daily copy",
  "每日文案配置已保存": "Daily copy settings saved",
  "未生成": "Not generated",
  "密码已重置": "Password reset",
  "模式配置": "Mode settings",
  "模型列表获取失败": "Failed to load model list",
  "模型配置": "Model settings",
  "模型日志": "Model logs",
  "默认 Codex 优先，失败后可回退官网会话链路。": "Defaults to Codex first, with ChatGPT Web conversation fallback on failure.",
  "配置": "Settings",
  "配置 ID 已存在": "Config ID already exists",
  "配置测试": "Config test",
  "配置获取模型": "Fetch models",
  "配置全站公开访问地址、站点名称、Logo、登录页标题图和登录背景；系统默认资源会保留为可选项。": "Configure the public access URL, site name, logo, login title image, and login backgrounds. System default assets remain available.",
  "配置全站公开访问地址、Remote MCP 授权有效期、站点名称和品牌资源。": "Configure the public access URL, Remote MCP authorization lifetimes, site name, and brand assets.",
  "配置审计": "Admin audit",
  "品牌设置": "Branding",
  "站点与品牌": "Site & branding",
  "品牌设置已保存": "Branding saved",
  "品牌图片已上传": "Brand image uploaded",
  "品牌资源已更新": "Brand asset updated",
  "品牌资源已删除": "Brand asset deleted",
  "平均耗时": "Average duration",
  "普通": "Normal",
  "启用": "Enabled",
  "启用 CPA 同步必须填写访问密码": "Access password is required to enable CPA sync",
  "启用 CPA 同步必须填写管理地址": "Admin URL is required to enable CPA sync",
  "启用代理必须填写代理地址": "Proxy URL is required when proxy is enabled",
  "启用后，允许使用代理的请求会走该地址；代理请求失败时按重试次数自动重试。": "When enabled, requests that allow proxying use this address. Failed proxy requests retry according to the retry count.",
  "启用渠道": "Enable channel",
  "启用用户": "Enabled users",
  "启用优化模型": "Enable optimization model",
  "启用账号": "Enable account",
  "请求日志": "Request logs",
  "请求数": "Requests",
  "请填写 Base URL 和 Endpoint Path": "Enter Base URL and Endpoint Path",
  "请填写供应商名称": "Enter provider name",
  "请填写模型名称": "Enter model name",
  "渠道耗时排行": "Channel duration ranking",
  "渠道名称不能为空": "Channel name is required",
  "渠道配置": "Channel settings",
  "渠道请求": "Channel requests",
  "渠道筛选": "Channel filter",
  "渠道失败排行": "Channel failure ranking",
  "渠道数": "Channels",
  "渠道已保存": "Channel saved",
  "渠道已启用": "Channel enabled",
  "渠道已删除": "Channel deleted",
  "渠道已停用": "Channel disabled",
  "渠道已新增": "Channel added",
  "全部": "All",
  "全部场景": "All scenarios",
  "全部团队": "All teams",
  "全部用户": "All users",
  "全部状态": "All statuses",
  "确认": "Confirm",
  "确认导入": "Confirm import",
  "确认关闭调试保存？关闭后新的图片编辑不会再保存这些调试文件。": "Disable debug saving? New image edits will no longer save these debug files.",
  "确认开启调试保存？开启后会保存编辑遮罩和请求信息，方便排查图片编辑问题。": "Enable debug saving? Edit masks and request information will be saved to help troubleshoot image editing issues.",
  "认证": "Authentication",
  "删除": "Delete",
  "删除备份": "Delete backup",
  "删除更新日志": "Delete changelog",
  "删除品牌资源": "Delete brand asset",
  "删除渠道": "Delete channel",
  "删除图片账号": "Delete image account",
  "删除团队": "Delete team",
  "删除优化模型": "Delete optimization model",
  "删除账号": "Delete account",
  "删除资源": "Delete asset",
  "标题": "Title",
  "时间": "Time",
  "文件": "File",
  "文件数": "Files",
  "目录": "Directory",
  "来源": "Source",
  "状态": "Status",
  "操作": "Actions",
  "团队": "Team",
  "用户": "User",
  "用户名": "Username",
  "账号": "Account",
  "邮箱": "Email",
  "英文版本待生成": "English version pending",
  "英文文案": "English copy",
  "手机号": "Phone",
  "会话": "Chats",
  "图片": "Images",
  "请求": "Requests",
  "类型": "Type",
  "渠道": "Channel",
  "调用方式": "Route",
  "最近错误": "Latest error",
  "最近登录": "Last login",
  "创建时间": "Created",
  "更新时间": "Updated",
  "错误": "Error",
  "上传 Logo": "Upload logo",
  "上传暗色背景": "Upload dark background",
  "上传标题图": "Upload title image",
  "上传浅色背景": "Upload light background",
  "上传图标": "Upload icon",
  "上传文件或粘贴 JSON 后会自动解析。": "Upload a file or paste JSON to parse it automatically.",
  "设为 Logo": "Set as logo",
  "设为图标": "Set as icon",
  "审核失败": "Review failed",
  "审核通过的签名名称，不带【】": "Approved signature name, without brackets",
  "生成": "Generate",
  "生成 / 编辑趋势": "Generation / edit trend",
  "生成失败": "Generation failed",
  "生成中": "Generating",
  "生图": "Image generation",
  "失败": "Failed",
  "失败分析": "Failure analysis",
  "失败率": "Failure rate",
  "失败数": "Failures",
  "失败自动切换": "Auto switch on failure",
  "失败自动切换：图片接口失败后自动切换": "Auto switch on failure: switch after image API failure",
  "失败总数": "Total failures",
  "使用代理": "Use proxy",
  "适合标准 API Key 或第三方兼容接口。": "Suitable for standard API keys or third-party compatible endpoints.",
  "适合日常使用，某条链路失败后自动尝试下一条。": "Suitable for daily use. If one route fails, the next route is tried automatically.",
  "适合只消耗 Codex/CPA 额度。": "Suitable when only Codex/CPA quota should be consumed.",
  "手动": "Manual",
  "手动凭据": "Manual credentials",
  "授权": "Authorization",
  "授权 / 认证": "Authorization / authentication",
  "数据备份": "Data backup",
  "数据统计": "Statistics",
  "刷新": "Refresh",
  "刷新额度": "Refresh quota",
  "刷新额度中": "Refreshing quota",
  "搜索灵感、提示词、用户、账号或风格": "Search inspiration, prompts, users, accounts, or styles",
  "搜索素材、用户、账号或标签": "Search assets, users, accounts, or tags",
  "搜索账号/用户名/邮箱/手机号": "Search account / username / email / phone",
  "素材名称": "Asset name",
  "素材名称自动生成失败": "Failed to generate asset name",
  "素材审核": "Asset review",
  "素材审核状态": "Asset review status",
  "素材已拒绝共享": "Asset sharing rejected",
  "素材已通过审核": "Asset approved",
  "随机": "Random",
  "腾讯云短信": "Tencent Cloud SMS",
  "腾讯云访问密钥 SecretId": "Tencent Cloud SecretId",
  "提示词翻译": "Prompt translation",
  "提示词模板": "Prompt template",
  "提示词优化": "Prompt optimization",
  "填写 CPA 管理地址和访问密码，从远端同步图片账号号池。": "Enter the CPA admin URL and access password to sync the image account pool from the remote service.",
  "跳过": "Skip",
  "停用": "Disable",
  "停用渠道": "Disable channel",
  "停用优化模型": "Disable optimization model",
  "通常为邮箱账号": "Usually the email account",
  "通过": "Approve",
  "通过灵感公开": "Approve inspiration",
  "通过素材共享": "Approve asset sharing",
  "同步失败": "Sync failed",
  "同步中": "Syncing",
  "统计分类": "Statistics category",
  "图片编辑": "Image editing",
  "图片产出": "Image output",
  "图片接口直连": "Direct image API",
  "图片接口直连：直接请求生成/编辑接口": "Direct image API: call generation/edit endpoints directly",
  "图片趋势": "Image trend",
  "图片生成": "Image generation",
  "图片数": "Images",
  "图片账号": "Image accounts",
  "图片账号已保存": "Image account saved",
  "图片账号已删除": "Image account deleted",
  "图片账号已新增": "Image account added",
  "图片总数": "Total images",
  "图生图": "Image-to-image",
  "团队管理": "Team management",
  "团队已保存": "Team saved",
  "团队已删除": "Team deleted",
  "团队已新增": "Team added",
  "完整提示词": "Full prompt",
  "未测试": "Not tested",
  "未发起": "Not started",
  "未记录": "Not recorded",
  "未记录用户": "No user recorded",
  "未配置账号": "No account configured",
  "未申请": "Not requested",
  "未填写邮箱": "No email",
  "未通过": "Rejected",
  "未选择目录": "No directory selected",
  "文件读取失败": "Failed to read file",
  "无": "No",
  "无限": "Unlimited",
  "系统": "System",
  "系统默认资源": "System default asset",
  "系统总览": "System overview",
  "先走 Codex Responses，失败再走官网会话链路": "Use Codex Responses first, then ChatGPT Web conversation fallback",
  "先走官网会话链路，失败再走 Codex Responses": "Use ChatGPT Web conversation first, then Codex Responses fallback",
  "向后排序": "Move back",
  "向前排序": "Move forward",
  "新的 API 渠道": "New API channel",
  "新的 CPA 渠道": "New CPA channel",
  "新的官网渠道": "New Web channel",
  "新的图片接口": "New image API",
  "新密码": "New password",
  "新增": "Add",
  "新增渠道": "Add channel",
  "新增账号": "Add account",
  "选择模型": "Select model",
  "选择目录": "Select directory",
  "选择团队": "Select team",
  "选择中": "Selecting",
  "移出轮播": "Remove from carousel",
  "已关闭": "Off",
  "已恢复系统默认品牌": "System default branding restored",
  "已开启": "On",
  "已启用": "Enabled",
  "已删除": "Deleted",
  "已生成": "Generated",
  "已跳过": "Skipped",
  "已通过": "Approved",
  "已同步": "Synced",
  "异常": "Abnormal",
  "异常放行": "Allow on error",
  "异常拦截": "Block on error",
  "异常时放行": "Allow when review fails",
  "异常时拦截": "Block when review fails",
  "用户加入灵感空间后先进入审核；通过后才进入公共灵感空间。": "User-submitted inspirations enter review first and appear publicly only after approval.",
  "用户请求数排行": "User request ranking",
  "用户失败数排行": "User failure ranking",
  "用户数": "Users",
  "用户图片数排行": "User image ranking",
  "用户团队": "Users and teams",
  "用户账号": "User accounts",
  "用户主动申请共享后才会出现在这里；审核通过后才进入共享素材区。": "Assets appear here after users request sharing. Approved assets enter the shared asset area.",
  "用于 C 端手机号注册验证码和手机号找回密码验证码发送，当前支持腾讯云短信。": "Used for mobile registration and password recovery verification codes. Tencent Cloud SMS is currently supported.",
  "用于 C 端邮箱注册验证码和找回密码验证码发送。": "Used for email registration and password recovery verification codes.",
  "用于本地排查图片编辑问题，平时保持关闭。": "Used for local image-edit debugging. Keep it off in normal use.",
  "用于测试 SMTP 是否可用，留空则发送到发件邮箱": "Used to test SMTP. Leave empty to send to the sender email.",
  "优化模型已保存": "Optimization model saved",
  "优化模型已启用": "Optimization model enabled",
  "优化模型已删除": "Optimization model deleted",
  "优化模型已停用": "Optimization model disabled",
  "优化模型已新增": "Optimization model added",
  "优先建议使用环境变量": "Environment variables are recommended",
  "优先使用高优先级账号": "Prefer high-priority accounts",
  "邮件配置": "Email settings",
  "邮件配置已保存": "Email settings saved",
  "有": "Yes",
  "预览": "Preview",
  "预览灵感": "Preview inspiration",
  "预览素材": "Preview asset",
  "远端": "Remote",
  "在可用账号之间轮流调用": "Rotate through available accounts",
  "暂无": "None",
  "暂无说明": "No description",
  "暂无同步记录": "No sync records",
  "暂无预览": "No preview",
  "粘贴内容": "Paste content",
  "账号池统计": "Account pool statistics",
  "账号池": "Account pool",
  "中文文案": "Chinese copy",
  "账号详情读取失败": "Failed to read account details",
  "账号已保存": "Account saved",
  "账号已删除": "Account deleted",
  "账号已新增": "Account added",
  "账号状态分布": "Account status distribution",
  "账号状态已更新": "Account status updated",
  "账号总数": "Total accounts",
  "真实记录存入配置数据库；静态 Markdown 文档由管理员自行维护，不参与系统读取。": "Real records are stored in the config database. Static Markdown documents are maintained manually by admins and are not read by the system.",
  "正常": "Normal",
  "审计": "Audit",
  "正在准备预览...": "Preparing preview...",
  "支持按账号、邮箱、手机号、团队和状态搜索筛选普通用户。": "Search and filter regular users by account, email, phone, team, and status.",
  "支持单个 JSON、JSON 数组、{ files: [...] } 或一行一个 JSON": "Supports one JSON object, a JSON array, { files: [...] }, or one JSON object per line",
  "只请求 ChatGPT 官网会话链路": "Use ChatGPT Web conversation route only",
  "只请求 codex-gpt-image-2 额度链路": "Use codex-gpt-image-2 quota route only",
  "只审核对话里用户提交的生图/图生图提示词。关闭后不会调用审核模型，也不会拦截请求。": "Only review user-submitted text-to-image and image-to-image prompts. When off, the review model is not called and requests are not blocked.",
  "只使用 ChatGPT 官网逆向渠道，可配置官网额度、Codex 额度或都走。": "Use only ChatGPT Web reverse-engineered channels. You can configure Web quota, Codex quota, or both.",
  "只使用 CPA 额度代理渠道。": "Use only CPA quota proxy channels.",
  "只使用 OpenAI 兼容或私有 API 直连渠道。": "Use only OpenAI-compatible or private direct API channels.",
  "只走 Codex": "Codex only",
  "只走官网": "Web only",
  "至少保留一张登录背景": "Keep at least one login background",
  "中": "Medium",
  "中国大陆 11 位手机号": "Mainland China 11-digit phone number",
  "重命名品牌资源": "Rename brand asset",
  "重命名资源": "Rename asset",
  "重试成功率": "Retry success rate",
  "重试请求": "Retry requests",
  "重试生成": "Retry generation",
  "重置密码": "Reset password",
  "周限额": "Weekly limit",
  "资源名称": "Asset name",
  "组织": "Organization",
  "内容": "Content",
  "自定义资源": "Custom asset",
  "自动": "Auto",
  "自动模式": "Auto mode",
  "自动生成失败": "Auto generation failed",
  "自助注册已关闭": "Self-service registration disabled",
  "自助注册已开启": "Self-service registration enabled",
  "昨日": "Yesterday",
  "左侧按团队筛选账号，右侧维护账号与团队信息。": "Filter accounts by team on the left and maintain account and team information on the right.",
  "AI 生成": "AI generated",
  "API 模式": "API mode",
  "API 直连": "Direct API",
  "ChatGPT 官网": "ChatGPT Web",
  "Codex 限流": "Codex limited",
  "Codex 优先": "Codex first",
  "Codex Responses 额度链路使用这个主模型；官网普通额度链路不使用。": "Codex Responses quota route uses this primary model. Normal Web quota routes do not.",
  "CPA 额度代理": "CPA quota proxy",
  "CPA 模式": "CPA mode",
  "CPA 同步": "CPA sync",
  "CPA 同步的 id_token / 账号认证信息": "CPA sync id_token / account auth info",
  "CPA 同步已触发": "CPA sync triggered",
  "CPA Bearer Key，可留空": "CPA Bearer Key, optional",
  "CPA、ChatGPT 官网和 API 直连统一按渠道维护。": "CPA, ChatGPT Web, and direct API are maintained as channels.",
  "DeepSeek 提示词优化": "DeepSeek prompt optimization",
  "OpenAI 兼容接口": "OpenAI-compatible endpoint",
  "Responses 接口": "Responses API",
  "Responses 接口：统一走 /v1/responses": "Responses API: use /v1/responses",
  "Responses 路由、CPA 遮罩编辑和自动回退到 Responses 时使用；普通 images_api 仍只发图片模型。": "Used by Responses routes, CPA mask editing, and automatic fallback to Responses. Normal images_api still sends only the image model."
};

const englishPhraseReplacements: Array<[string, string]> = [
  ["当前统计范围：", "Current range: "],
  ["最近同步：", "Last sync: "],
  ["最近更新：", "Last updated: "],
  ["下次 ", "Next "],
  ["最近 ", "Recent "],
  ["暂无错误摘要", "No error summary"],
  ["暂无团队数据", "No team data"],
  ["暂无渠道请求数据", "No channel request data"],
  ["暂无失败记录", "No failure records"],
  ["暂无备份记录", "No backup records"],
  ["暂无账号", "No accounts"],
  ["暂无数据", "No data"],
  ["等待首次备份", "Waiting for first backup"],
  ["未记录账号", "No account recorded"],
  ["未记录渠道", "No channel recorded"],
  ["未记录方式", "No route recorded"],
  ["未知", "Unknown"],
  ["进行中", "Running"],
  ["平均耗时 ", "Average duration "],
  ["耗时 ", "Duration "],
  ["启用 ", "Enabled "],
  ["管理 ", "Admin "],
  ["生成 ", "Generated "],
  ["编辑 ", "Edited "],
  ["重试生成 ", "Retry generation "],
  ["失败 ", "Failed "],
  ["重试 ", "Retry "],
  ["成功 ", "Success "],
  ["自动 ", "Auto "],
  ["手动 ", "Manual "],
  ["用户 ", "Users "],
  ["请求 ", "Requests "],
  ["图片 ", "Images "],
  ["文件 ", "Files "],
  ["成功率 ", "Success rate "],
  ["Codex 限流/异常 ", "Codex limited/abnormal "],
  ["CPA 同步成功：", "CPA sync succeeded: "],
  ["新增 ", "Added "],
  ["更新 ", "Updated "],
  ["跳过 ", "Skipped "],
  [" 个，", ", "],
  ["，", ", "],
  [" 个", ""],
  ["至", "to"]
];

const configCopyLocales = ["ja-JP", "ko-KR", "es-ES", "fr-FR", "de-DE", "pt-BR", "ru-RU", "fa-IR"] as const;
type ConfigCopyLocale = (typeof configCopyLocales)[number];
type LocaleTextRow = readonly [string, ...string[]];

const localizedTermRows: LocaleTextRow[] = [
  ["数据统计", "データ統計", "데이터 통계", "Estadísticas", "Statistiques", "Statistiken", "Estatísticas", "Статистика", "آمار"],
  ["用户账号", "ユーザーアカウント", "사용자 계정", "Cuentas de usuario", "Comptes utilisateur", "Benutzerkonten", "Contas de usuário", "Учетные записи", "حساب‌های کاربری"],
  ["团队管理", "チーム管理", "팀 관리", "Gestión de equipos", "Gestion des équipes", "Teamverwaltung", "Gestão de equipes", "Управление командами", "مدیریت تیم‌ها"],
  ["素材审核", "素材レビュー", "소재 검토", "Revisión de recursos", "Revue des ressources", "Asset-Prüfung", "Revisão de recursos", "Проверка материалов", "بررسی منابع"],
  ["灵感审核", "インスピレーションレビュー", "영감 검토", "Revisión de inspiración", "Revue des inspirations", "Inspirationsprüfung", "Revisão de inspirações", "Проверка вдохновения", "بررسی الهام"],
  ["空白页文案", "空白ページ文言", "빈 페이지 문구", "Texto de página vacía", "Texte de page vide", "Leerseitentexte", "Texto da página vazia", "Тексты пустой страницы", "متن صفحه خالی"],
  ["中文文案", "中国語文言", "중국어 문구", "Texto chino", "Texte chinois", "Chinesischer Text", "Texto em chinês", "Китайский текст", "متن چینی"],
  ["英文文案", "英語文言", "영어 문구", "Texto inglés", "Texte anglais", "Englischer Text", "Texto em inglês", "Английский текст", "متن انگلیسی"],
  ["英文版本待生成", "英語版は未生成", "영어 버전 생성 대기", "Versión inglesa pendiente", "Version anglaise en attente", "Englische Version ausstehend", "Versão em inglês pendente", "Английская версия ожидает создания", "نسخه انگلیسی در انتظار تولید"],
  ["未生成", "未生成", "생성 안 됨", "No generado", "Non généré", "Nicht generiert", "Não gerado", "Не создано", "تولید نشده"],
  ["更新日志", "変更履歴", "변경 기록", "Registro de cambios", "Journal des changements", "Änderungsprotokoll", "Histórico de alterações", "Журнал изменений", "گزارش تغییرات"],
  ["同步英文日志", "英語の変更履歴を同期", "영문 변경 기록 동기화", "Sincronizar el registro en inglés", "Synchroniser le journal en anglais", "Englische Änderungsprotokolle synchronisieren", "Sincronizar histórico em inglês", "Синхронизировать журнал на английском", "همگام‌سازی گزارش تغییرات انگلیسی"],
  ["账号池", "アカウントプール", "계정 풀", "Pool de cuentas", "Pool de comptes", "Account-Pool", "Pool de contas", "Пул аккаунтов", "مخزن حساب‌ها"],
  ["渠道配置", "チャネル設定", "채널 설정", "Configuración de canales", "Configuration des canaux", "Kanalkonfiguration", "Configuração de canais", "Настройки каналов", "تنظیمات کانال"],
  ["模型配置", "モデル設定", "모델 설정", "Configuración de modelos", "Configuration des modèles", "Modellkonfiguration", "Configuração de modelos", "Настройки моделей", "تنظیمات مدل"],
  ["供应商配置", "プロバイダー設定", "공급자 설정", "Configuración de proveedores", "Configuration des fournisseurs", "Anbieter-Einstellungen", "Configuração de provedores", "Настройки поставщиков", "تنظیمات ارائه‌دهنده"],
  ["场景分配", "シナリオ割り当て", "시나리오 할당", "Asignación de escenarios", "Affectation des scénarios", "Szenario-Zuweisung", "Atribuição de cenários", "Назначение сценариев", "تخصیص سناریو"],
  ["安全审核", "安全レビュー", "안전 검토", "Revisión de seguridad", "Revue de sécurité", "Sicherheitsprüfung", "Revisão de segurança", "Проверка безопасности", "بررسی ایمنی"],
  ["模式配置", "モード設定", "모드 설정", "Configuración de modo", "Configuration du mode", "Moduskonfiguration", "Configuração de modo", "Настройки режима", "تنظیمات حالت"],
  ["CPA 同步", "CPA 同期", "CPA 동기화", "Sincronización CPA", "Synchronisation CPA", "CPA-Sync", "Sincronização CPA", "Синхронизация CPA", "همگام‌سازی CPA"],
  ["品牌设置", "ブランド設定", "브랜드 설정", "Marca", "Marque", "Branding", "Marca", "Брендинг", "برندسازی"],
  ["站点与品牌", "サイトとブランド", "사이트 및 브랜드", "Sitio y marca", "Site et marque", "Website & Branding", "Site e marca", "Сайт и бренд", "سایت و برند"],
  ["邮件配置", "メール設定", "메일 설정", "Correo", "E-mail", "E-Mail", "E-mail", "Почта", "ایمیل"],
  ["短信配置", "SMS 設定", "SMS 설정", "SMS", "SMS", "SMS", "SMS", "SMS", "پیامک"],
  ["数据备份", "データバックアップ", "데이터 백업", "Copia de seguridad", "Sauvegarde", "Datensicherung", "Backup de dados", "Резервное копирование", "پشتیبان‌گیری داده"],
  ["代理配置", "プロキシ設定", "프록시 설정", "Proxy", "Proxy", "Proxy", "Proxy", "Прокси", "پروکسی"],
  ["调试配置", "デバッグ設定", "디버그 설정", "Depuración", "Débogage", "Debug", "Depuração", "Отладка", "اشکال‌زدایی"],
  ["模型日志", "モデルログ", "모델 로그", "Registros de modelo", "Journaux de modèle", "Modellprotokolle", "Logs de modelo", "Логи моделей", "گزارش‌های مدل"],
  ["请求日志", "リクエストログ", "요청 로그", "Registros de solicitudes", "Journaux de requêtes", "Anfrageprotokolle", "Logs de requisições", "Логи запросов", "گزارش‌های درخواست"],
  ["审计", "監査", "감사", "Auditoría", "Audit", "Audit", "Auditoria", "Аудит", "حسابرسی"],
  ["按时间范围查看系统整体、用户团队、图片产出、渠道请求、图片账号和失败情况。", "期間ごとにシステム全体、ユーザーとチーム、画像出力、チャネルリクエスト、画像アカウント、失敗状況を確認します。", "기간별로 시스템 전체, 사용자와 팀, 이미지 산출, 채널 요청, 이미지 계정, 실패 현황을 확인합니다.", "Consulta por rango de fechas el sistema, usuarios y equipos, producción de imágenes, solicitudes de canales, cuentas de imagen y fallos.", "Consultez par période le système, les utilisateurs et équipes, la production d’images, les requêtes de canaux, les comptes image et les échecs.", "Zeigt nach Zeitraum System, Benutzer und Teams, Bildausgabe, Kanalanfragen, Bildkonten und Fehler.", "Veja por período o sistema, usuários e equipes, produção de imagens, requisições de canais, contas de imagem e falhas.", "Просматривайте по периоду систему, пользователей и команды, выпуск изображений, запросы каналов, аккаунты изображений и сбои.", "بر اساس بازه زمانی، وضعیت سیستم، کاربران و تیم‌ها، خروجی تصویر، درخواست‌های کانال، حساب‌های تصویر و خطاها را ببینید."],
  ["查看用户活跃、团队产出和管理权限账号分布。", "ユーザーのアクティビティ、チームの出力、管理権限アカウントの分布を確認します。", "사용자 활동, 팀 산출, 관리자 권한 계정 분포를 확인합니다.", "Consulta actividad de usuarios, producción de equipos y distribución de permisos de administración.", "Consultez l’activité des utilisateurs, la production des équipes et la répartition des accès administrateur.", "Zeigt Benutzeraktivität, Teamleistung und Verteilung der Admin-Berechtigungen.", "Veja atividade de usuários, produção de equipes e distribuição de permissões administrativas.", "Просматривайте активность пользователей, результаты команд и распределение прав администратора.", "فعالیت کاربران، خروجی تیم‌ها و توزیع دسترسی مدیریت را ببینید."],
  ["按生成、编辑、用户、团队和渠道观察图片产出。", "生成、編集、ユーザー、チーム、チャネル別に画像出力を確認します。", "생성, 편집, 사용자, 팀, 채널별 이미지 산출을 확인합니다.", "Observa la producción de imágenes por generación, edición, usuario, equipo y canal.", "Analysez la production d’images par génération, édition, utilisateur, équipe et canal.", "Betrachtet Bildausgaben nach Generierung, Bearbeitung, Benutzer, Team und Kanal.", "Observe a produção de imagens por geração, edição, usuário, equipe e canal.", "Анализируйте выпуск изображений по генерации, редактированию, пользователям, командам и каналам.", "خروجی تصویر را بر اساس تولید، ویرایش، کاربر، تیم و کانال بررسی کنید."],
  ["按渠道、调用方式和具体渠道查看请求质量。", "チャネル、呼び出し方式、具体的なプロバイダー別にリクエスト品質を確認します。", "채널, 호출 방식, 구체 채널별 요청 품질을 확인합니다.", "Consulta la calidad de solicitudes por canal, modo de llamada y proveedor.", "Consultez la qualité des requêtes par canal, mode d’appel et fournisseur.", "Zeigt die Anfragequalität nach Kanal, Aufrufart und Anbieter.", "Veja a qualidade das requisições por canal, modo de chamada e provedor.", "Просматривайте качество запросов по каналам, способам вызова и провайдерам.", "کیفیت درخواست‌ها را بر اساس کانال، روش فراخوانی و ارائه‌دهنده ببینید."],
  ["查看号池状态、本地调用排行和最近 CPA 同步结果。", "アカウントプール状態、ローカル呼び出しランキング、最近の CPA 同期結果を確認します。", "계정 풀 상태, 로컬 호출 순위, 최근 CPA 동기화 결과를 확인합니다.", "Consulta estado del pool, rankings de llamadas locales y sincronización CPA reciente.", "Consultez l’état du pool, les classements d’appels locaux et la dernière synchronisation CPA.", "Zeigt Poolstatus, lokale Aufrufranglisten und aktuelle CPA-Sync-Ergebnisse.", "Veja status do pool, rankings de chamadas locais e sincronização CPA recente.", "Просматривайте состояние пула, рейтинги локальных вызовов и последние результаты CPA-синхронизации.", "وضعیت مخزن، رتبه‌بندی فراخوانی محلی و آخرین نتیجه همگام‌سازی CPA را ببینید."],
  ["定位高频错误、失败渠道和最近失败请求。", "頻出エラー、失敗チャネル、最近の失敗リクエストを特定します。", "빈번한 오류, 실패 채널, 최근 실패 요청을 파악합니다.", "Localiza errores frecuentes, canales fallidos y solicitudes fallidas recientes.", "Identifiez les erreurs fréquentes, les canaux en échec et les requêtes échouées récentes.", "Findet häufige Fehler, fehlgeschlagene Kanäle und aktuelle fehlgeschlagene Anfragen.", "Localize erros frequentes, canais com falha e requisições recentes com falha.", "Находите частые ошибки, проблемные каналы и последние неудачные запросы.", "خطاهای پرتکرار، کانال‌های ناموفق و درخواست‌های ناموفق اخیر را پیدا کنید."],
  ["全部", "すべて", "전체", "Todo", "Tout", "Alle", "Tudo", "Все", "همه"],
  ["今日", "今日", "오늘", "Hoy", "Aujourd’hui", "Heute", "Hoje", "Сегодня", "امروز"],
  ["今日实时图片", "今日のリアルタイム画像", "오늘 실시간 이미지", "Imágenes de hoy", "Images du jour", "Bilder heute", "Imagens de hoje", "Изображения сегодня", "تصاویر امروز"],
  ["昨日", "昨日", "어제", "Ayer", "Hier", "Gestern", "Ontem", "Вчера", "دیروز"],
  ["近 7 天", "過去 7 日", "최근 7일", "Últimos 7 días", "7 derniers jours", "Letzte 7 Tage", "Últimos 7 dias", "Последние 7 дней", "۷ روز اخیر"],
  ["近 30 天", "過去 30 日", "최근 30일", "Últimos 30 días", "30 derniers jours", "Letzte 30 Tage", "Últimos 30 dias", "Последние 30 дней", "۳۰ روز اخیر"],
  ["近 1 年", "過去 1 年", "최근 1년", "Último año", "Dernière année", "Letztes Jahr", "Último ano", "Последний год", "۱ سال اخیر"],
  ["本月", "今月", "이번 달", "Este mes", "Ce mois-ci", "Dieser Monat", "Este mês", "Этот месяц", "این ماه"],
  ["今年", "今年", "올해", "Este año", "Cette année", "Dieses Jahr", "Este ano", "Этот год", "امسال"],
  ["用户团队", "ユーザーとチーム", "사용자와 팀", "Usuarios y equipos", "Utilisateurs et équipes", "Benutzer und Teams", "Usuários e equipes", "Пользователи и команды", "کاربران و تیم‌ها"],
  ["图片产出", "画像出力", "이미지 산출", "Producción de imágenes", "Production d’images", "Bildausgabe", "Produção de imagens", "Выпуск изображений", "خروجی تصویر"],
  ["渠道请求", "チャネルリクエスト", "채널 요청", "Solicitudes de canales", "Requêtes de canaux", "Kanalanfragen", "Requisições de canais", "Запросы каналов", "درخواست‌های کانال"],
  ["图片账号", "画像アカウント", "이미지 계정", "Cuentas de imagen", "Comptes image", "Bildkonten", "Contas de imagem", "Аккаунты изображений", "حساب‌های تصویر"],
  ["失败分析", "失敗分析", "실패 분석", "Análisis de fallos", "Analyse des échecs", "Fehleranalyse", "Análise de falhas", "Анализ сбоев", "تحلیل خطا"],
  ["系统总览", "システム概要", "시스템 개요", "Resumen del sistema", "Vue d’ensemble du système", "Systemübersicht", "Visão geral do sistema", "Обзор системы", "نمای کلی سیستم"],
  ["生成", "生成", "생성", "Generación", "Génération", "Generierung", "Geração", "Генерация", "تولید"],
  ["编辑", "編集", "편집", "Edición", "Édition", "Bearbeitung", "Edição", "Редактирование", "ویرایش"],
  ["请求", "リクエスト", "요청", "Solicitudes", "Requêtes", "Anfragen", "Requisições", "Запросы", "درخواست‌ها"],
  ["重试", "再試行", "재시도", "Reintentos", "Nouvelles tentatives", "Wiederholungen", "Tentativas", "Повторы", "تلاش مجدد"],
  ["失败", "失敗", "실패", "Fallos", "Échecs", "Fehler", "Falhas", "Сбои", "خطاها"],
  ["成功", "成功", "성공", "Éxito", "Succès", "Erfolg", "Sucesso", "Успех", "موفقیت"],
  ["成功率", "成功率", "성공률", "Tasa de éxito", "Taux de réussite", "Erfolgsrate", "Taxa de sucesso", "Успешность", "نرخ موفقیت"],
  ["平均耗时", "平均時間", "평균 소요 시간", "Duración media", "Durée moyenne", "Durchschnittsdauer", "Duração média", "Среднее время", "میانگین زمان"],
  ["渠道", "チャネル", "채널", "Canal", "Canal", "Kanal", "Canal", "Канал", "کانال"],
  ["类型", "種類", "유형", "Tipo", "Type", "Typ", "Tipo", "Тип", "نوع"],
  ["最近错误", "最新エラー", "최근 오류", "Error reciente", "Dernière erreur", "Letzter Fehler", "Erro recente", "Последняя ошибка", "آخرین خطا"],
  ["时间", "時刻", "시간", "Hora", "Heure", "Zeit", "Hora", "Время", "زمان"],
  ["用户", "ユーザー", "사용자", "Usuario", "Utilisateur", "Benutzer", "Usuário", "Пользователь", "کاربر"],
  ["团队", "チーム", "팀", "Equipo", "Équipe", "Team", "Equipe", "Команда", "تیم"],
  ["调用方式", "呼び出し方式", "호출 방식", "Modo de llamada", "Mode d’appel", "Aufrufart", "Modo de chamada", "Способ вызова", "روش فراخوانی"],
  ["错误", "エラー", "오류", "Error", "Erreur", "Fehler", "Erro", "Ошибка", "خطا"],
  ["状态", "状態", "상태", "Estado", "Statut", "Status", "Status", "Статус", "وضعیت"],
  ["操作", "操作", "작업", "Acciones", "Actions", "Aktionen", "Ações", "Действия", "عملیات"],
  ["文件", "ファイル", "파일", "Archivo", "Fichier", "Datei", "Arquivo", "Файл", "فایل"],
  ["目录", "ディレクトリ", "디렉터리", "Directorio", "Dossier", "Verzeichnis", "Diretório", "Каталог", "پوشه"],
  ["来源", "ソース", "출처", "Origen", "Source", "Quelle", "Origem", "Источник", "منبع"],
  ["文件数", "ファイル数", "파일 수", "Archivos", "Nombre de fichiers", "Dateien", "Arquivos", "Файлы", "تعداد فایل"],
  ["耗时", "所要時間", "소요 시간", "Duración", "Durée", "Dauer", "Duração", "Длительность", "مدت زمان"],
  ["启用", "有効", "활성화", "Activado", "Activé", "Aktiviert", "Ativado", "Включено", "فعال"],
  ["禁用", "無効", "비활성화", "Desactivado", "Désactivé", "Deaktiviert", "Desativado", "Отключено", "غیرفعال"],
  ["已启用", "有効", "활성화됨", "Activado", "Activé", "Aktiviert", "Ativado", "Включено", "فعال"],
  ["已关闭", "オフ", "꺼짐", "Desactivado", "Désactivé", "Aus", "Desativado", "Выключено", "خاموش"],
  ["已开启", "オン", "켜짐", "Activado", "Activé", "Ein", "Ativado", "Включено", "روشن"],
  ["保存配置", "設定を保存", "설정 저장", "Guardar configuración", "Enregistrer la configuration", "Einstellungen speichern", "Salvar configuração", "Сохранить настройки", "ذخیره تنظیمات"],
  ["保存", "保存", "저장", "Guardar", "Enregistrer", "Speichern", "Salvar", "Сохранить", "ذخیره"],
  ["新增", "追加", "추가", "Añadir", "Ajouter", "Hinzufügen", "Adicionar", "Добавить", "افزودن"],
  ["删除", "削除", "삭제", "Eliminar", "Supprimer", "Löschen", "Excluir", "Удалить", "حذف"],
  ["关闭", "閉じる", "닫기", "Cerrar", "Fermer", "Schließen", "Fechar", "Закрыть", "بستن"],
  ["确认", "確認", "확인", "Confirmar", "Confirmer", "Bestätigen", "Confirmar", "Подтвердить", "تأیید"],
  ["刷新", "更新", "새로고침", "Actualizar", "Actualiser", "Aktualisieren", "Atualizar", "Обновить", "بازخوانی"],
  ["发送中", "送信中", "전송 중", "Enviando", "Envoi en cours", "Senden", "Enviando", "Отправка", "در حال ارسال"],
  ["保存中", "保存中", "저장 중", "Guardando", "Enregistrement", "Speichern", "Salvando", "Сохранение", "در حال ذخیره"],
  ["暂无数据", "データがありません", "데이터 없음", "Sin datos", "Aucune donnée", "Keine Daten", "Sem dados", "Нет данных", "داده‌ای نیست"],
  ["暂无账号", "アカウントがありません", "계정 없음", "Sin cuentas", "Aucun compte", "Keine Konten", "Sem contas", "Нет аккаунтов", "حسابی نیست"],
  ["未记录", "未記録", "기록 없음", "Sin registro", "Non enregistré", "Nicht erfasst", "Não registrado", "Не записано", "ثبت نشده"],
  ["未知", "不明", "알 수 없음", "Desconocido", "Inconnu", "Unbekannt", "Desconhecido", "Неизвестно", "نامشخص"],
  ["正常", "正常", "정상", "Normal", "Normal", "Normal", "Normal", "Норма", "عادی"],
  ["异常", "異常", "이상", "Anormal", "Anormal", "Abnormal", "Anormal", "Ошибка", "غیرعادی"],
  ["可用", "利用可能", "사용 가능", "Disponible", "Disponible", "Verfügbar", "Disponível", "Доступно", "در دسترس"],
  ["Codex 限流", "Codex 制限中", "Codex 제한", "Límite Codex", "Limite Codex", "Codex-Limit", "Limite Codex", "Лимит Codex", "محدودیت Codex"],
  ["未通过", "却下", "거부됨", "Rechazado", "Rejeté", "Abgelehnt", "Rejeitado", "Отклонено", "رد شده"],
  ["待审核", "レビュー待ち", "검토 대기", "Pendiente", "En attente", "Ausstehend", "Pendente", "На проверке", "در انتظار بررسی"],
  ["已通过", "承認済み", "승인됨", "Aprobado", "Approuvé", "Genehmigt", "Aprovado", "Одобрено", "تأیید شده"],
  ["通过", "承認", "승인", "Aprobar", "Approuver", "Genehmigen", "Aprovar", "Одобрить", "تأیید"],
  ["拒绝", "拒否", "거부", "Rechazar", "Rejeter", "Ablehnen", "Rejeitar", "Отклонить", "رد کردن"]
];

const localizedConfigCopy: Partial<Record<ConfigCopyLocale, Record<string, string>>> = {};

for (const [source, ...translations] of localizedTermRows) {
  configCopyLocales.forEach((locale, index) => {
    (localizedConfigCopy[locale] ??= {})[source] = translations[index] ?? source;
  });
}

const localizedPhraseRows: LocaleTextRow[] = [
  ["当前统计范围：", "現在の範囲: ", "현재 범위: ", "Rango actual: ", "Période actuelle : ", "Aktueller Zeitraum: ", "Intervalo atual: ", "Текущий диапазон: ", "بازه فعلی: "],
  ["最近同步：", "最新同期: ", "최근 동기화: ", "Última sincronización: ", "Dernière synchronisation : ", "Letzte Synchronisierung: ", "Última sincronização: ", "Последняя синхронизация: ", "آخرین همگام‌سازی: "],
  ["最近更新：", "最終更新: ", "최근 업데이트: ", "Última actualización: ", "Dernière mise à jour : ", "Letzte Aktualisierung: ", "Última atualização: ", "Последнее обновление: ", "آخرین به‌روزرسانی: "],
  ["下次 ", "次回 ", "다음 ", "Próximo ", "Prochaine ", "Nächste ", "Próximo ", "Следующее ", "بعدی "],
  ["最近 ", "最近 ", "최근 ", "Reciente ", "Récent ", "Aktuell ", "Recente ", "Недавно ", "اخیر "],
  ["平均耗时 ", "平均時間 ", "평균 소요 시간 ", "Duración media ", "Durée moyenne ", "Durchschnittsdauer ", "Duração média ", "Среднее время ", "میانگین زمان "],
  ["耗时 ", "所要時間 ", "소요 시간 ", "Duración ", "Durée ", "Dauer ", "Duração ", "Длительность ", "مدت زمان "],
  ["启用 ", "有効 ", "활성 ", "Activado ", "Activé ", "Aktiviert ", "Ativado ", "Включено ", "فعال "],
  ["管理 ", "管理 ", "관리 ", "Admin ", "Admin ", "Admin ", "Admin ", "Админ ", "مدیریت "],
  ["生成 ", "生成 ", "생성 ", "Generado ", "Généré ", "Generiert ", "Gerado ", "Создано ", "تولید "],
  ["编辑 ", "編集 ", "편집 ", "Editado ", "Édité ", "Bearbeitet ", "Editado ", "Изменено ", "ویرایش "],
  ["重试生成 ", "再生成 ", "재생성 ", "Regeneración ", "Régénération ", "Retry-Generierung ", "Regeneração ", "Повторная генерация ", "تولید مجدد "],
  ["失败 ", "失敗 ", "실패 ", "Fallos ", "Échecs ", "Fehler ", "Falhas ", "Сбои ", "خطا "],
  ["重试 ", "再試行 ", "재시도 ", "Reintentos ", "Tentatives ", "Wiederholungen ", "Tentativas ", "Повторы ", "تلاش مجدد "],
  ["成功 ", "成功 ", "성공 ", "Éxito ", "Succès ", "Erfolg ", "Sucesso ", "Успех ", "موفق "],
  ["自动 ", "自動 ", "자동 ", "Auto ", "Auto ", "Automatisch ", "Auto ", "Авто ", "خودکار "],
  ["手动 ", "手動 ", "수동 ", "Manual ", "Manuel ", "Manuell ", "Manual ", "Вручную ", "دستی "],
  ["用户 ", "ユーザー ", "사용자 ", "Usuarios ", "Utilisateurs ", "Benutzer ", "Usuários ", "Пользователи ", "کاربر "],
  ["请求 ", "リクエスト ", "요청 ", "Solicitudes ", "Requêtes ", "Anfragen ", "Requisições ", "Запросы ", "درخواست "],
  ["图片 ", "画像 ", "이미지 ", "Imágenes ", "Images ", "Bilder ", "Imagens ", "Изображения ", "تصویر "],
  ["文件 ", "ファイル ", "파일 ", "Archivos ", "Fichiers ", "Dateien ", "Arquivos ", "Файлы ", "فایل "],
  ["成功率 ", "成功率 ", "성공률 ", "Tasa de éxito ", "Taux de réussite ", "Erfolgsrate ", "Taxa de sucesso ", "Успешность ", "نرخ موفقیت "],
  ["Codex 限流/异常 ", "Codex 制限/異常 ", "Codex 제한/이상 ", "Límite/anomalía Codex ", "Limite/anomalie Codex ", "Codex-Limit/Fehler ", "Limite/anomalia Codex ", "Лимит/ошибка Codex ", "محدودیت/خطای Codex "],
  ["CPA 同步成功：", "CPA 同期成功: ", "CPA 동기화 성공: ", "Sincronización CPA correcta: ", "Synchronisation CPA réussie : ", "CPA-Sync erfolgreich: ", "Sincronização CPA concluída: ", "CPA-синхронизация успешна: ", "همگام‌سازی CPA موفق: "],
  ["新增 ", "追加 ", "추가 ", "Añadido ", "Ajouté ", "Hinzugefügt ", "Adicionado ", "Добавлено ", "افزوده "],
  ["更新 ", "更新 ", "업데이트 ", "Actualizado ", "Mis à jour ", "Aktualisiert ", "Atualizado ", "Обновлено ", "به‌روزرسانی "],
  ["跳过 ", "スキップ ", "건너뜀 ", "Omitido ", "Ignoré ", "Übersprungen ", "Ignorado ", "Пропущено ", "نادیده "],
  ["succeeded", "成功", "성공", "correcto", "réussi", "erfolgreich", "concluído", "успешно", "موفق"],
  ["failed", "失敗", "실패", "fallido", "échoué", "fehlgeschlagen", "falhou", "сбой", "ناموفق"],
  ["running", "実行中", "실행 중", "en ejecución", "en cours", "läuft", "em execução", "выполняется", "در حال اجرا"],
  ["，", "、", ", ", ", ", ", ", ", ", ", ", ", ", "، "],
  [" 个", " 件", "개", "", "", "", "", "", ""],
  ["至", "〜", "부터", "a", "à", "bis", "até", "до", "تا"]
];

const localizedPhraseReplacements: Partial<Record<ConfigCopyLocale, Array<[string, string]>>> = {};

for (const [source, ...translations] of localizedPhraseRows) {
  configCopyLocales.forEach((locale, index) => {
    (localizedPhraseReplacements[locale] ??= []).push([source, translations[index] ?? source]);
  });
}

const extraEnglishConfigCopy: Record<string, string> = {
  "分类管理": "Category management",
  "统一维护灵感空间风格与素材库标签；前台仍可新增，后台修改会同步影响全站筛选和自动推荐。": "Manage Inspiration styles and asset tags in one place. Users can still add items from the main app, while admin changes update filters and automatic suggestions site-wide.",
  "分类类型": "Category type",
  "灵感风格": "Inspiration styles",
  "素材标签": "Asset tags",
  "搜索灵感风格": "Search inspiration styles",
  "搜索素材标签": "Search asset tags",
  "新增灵感风格": "Add inspiration style",
  "新增素材标签": "Add asset tag",
  "顺序": "Order",
  "名称": "Name",
  "关联内容": "Linked content",
  "推荐缓存": "Suggestion cache",
  "排序": "Reorder",
  "上移": "Move up",
  "下移": "Move down",
  "清除搜索后排序": "Clear search before reordering",
  "改名": "Rename",
  "合并": "Merge",
  "合并到其他分类": "Merge into another category",
  "存在引用，请先合并": "Referenced items must be merged first",
  "分类加载中...": "Loading categories...",
  "暂无匹配分类": "No matching categories",
  "合并到": "Merge into",
  "确认合并": "Confirm merge",
  "合并中": "Merging",
  "支持按账号、邮箱、手机号、团队和状态搜索筛选普通用户。": "Search and filter regular users by account, email, phone, team, and status.",
  "关闭后 C 端无法获取注册验证码或完成注册；后台新增账号不受影响。": "When disabled, end users cannot get registration codes or complete registration. Admin-created accounts are not affected.",
  "搜索账号/用户名/邮箱/手机号": "Search account / username / email / phone",
  "新增账号": "Add account",
  "用户名": "Username",
  "账号": "Account",
  "邮箱": "Email",
  "手机号": "Phone",
  "对话": "Chats",
  "左侧按团队筛选账号，右侧维护账号与团队信息。": "Filter accounts by team on the left, and maintain accounts and team information on the right.",
  "新增团队": "Add team",
  "全部分组": "All groups",
  "默认团队": "Default team",
  "团队名称": "Team name",
  "团队说明": "Team description",
  "用户主动申请共享后才会出现在这里；审核通过后才进入共享素材区。": "Assets appear here after users request sharing. Approved assets enter the shared asset area.",
  "关闭后，新提交共享的素材会直接公开；历史待审素材仍保留当前状态。": "When disabled, newly shared assets are published directly. Existing pending assets keep their current status.",
  "素材审核状态": "Asset review status",
  "搜索素材、用户、账号或标签": "Search assets, users, accounts, or tags",
  "素材": "Asset",
  "提交用户": "Submitted by",
  "标签": "Tags",
  "提交时间": "Submitted at",
  "审核时间": "Reviewed at",
  "用户加入灵感空间后先进入审核；通过后才进入公共灵感空间。": "User-submitted inspirations enter review first and appear publicly only after approval.",
  "关闭后，新加入灵感会直接公开；历史待审灵感仍保留当前状态。": "When disabled, new inspirations are published directly. Existing pending inspirations keep their current status.",
  "灵感审核状态": "Inspiration review status",
  "搜索灵感、提示词、用户、账号或风格": "Search inspiration, prompts, users, accounts, or styles",
  "灵感": "Inspiration",
  "风格": "Style",
  "空白页每日文案": "Daily blank-page copy",
  "开启后每天凌晨由启用的语言模型生成生图相关互动文案；关闭或失败时继续使用本地固定文案。": "When enabled, the active language model generates image-related starter copy every morning. When disabled or failed, local fixed copy remains in use.",
  "生成数量": "Generation count",
  "立即更新文案": "Update copy now",
  "今日文案": "Today's copy",
  "真实记录存入配置数据库；静态 Markdown 文档由管理员自行维护，不参与系统读取。": "Real records are stored in the config database. Static Markdown documents are maintained manually by admins and are not read by the system.",
  "新增日志": "Add changelog",
  "账号管理": "Account management",
  "维护图片账号号池、额度、优先级和同步状态。": "Maintain the image account pool, quota, priority, and sync status.",
  "全部刷新额度": "Refresh all quotas",
  "批量导入": "Batch import",
  "订阅套餐": "Plan",
  "Codex 额度": "Codex quota",
  "CPA统计": "CPA stats",
  "本地统计": "Local stats",
  "认证信息": "Auth info",
  "优先级": "Priority",
  "同步": "Sync",
  "CPA、ChatGPT 官网和 API 直连统一按渠道维护。": "CPA, ChatGPT Web, and direct API are maintained as channels.",
  "调用策略": "Call strategy",
  "账号 / 地址": "Account / URL",
  "独立维护 AI 优化提示词使用的 OpenAI Chat Completions 兼容语言模型，不复用图片渠道。": "Maintain the OpenAI Chat Completions-compatible model used for AI prompt optimization separately from image channels.",
  "新增供应商": "Add provider",
  "供应商": "Provider",
  "地址": "URL",
  "参数": "Parameters",
  "只审核对话里用户提交的生图/图生图提示词。关闭后不会调用审核模型，也不会拦截请求。": "Only review user-submitted text-to-image and image-to-image prompts. When off, the review model is not called and requests are not blocked.",
  "文本审核总开关": "Text review master switch",
  "开启后在提交生图前审核用户提示词，命中拦截时不调用图片渠道。": "When enabled, user prompts are reviewed before image generation. Blocked prompts do not call image channels.",
  "审核异常策略": "Review failure policy",
  "异常时放行": "Allow on review failure",
  "异常时拦截": "Block on review failure",
  "拦截提示文案": "Block message",
  "刷新记录": "Refresh records",
  "场景": "Scenario",
  "结论": "Decision",
  "风险": "Risk",
  "提示词": "Prompt",
  "原因": "Reason",
  "模型/耗时": "Model / duration",
  "控制图片生成整体从哪类渠道选路。": "Control which channel type image generation routes through.",
  "请求策略": "Request policy",
  "图片接口调用或图片结果保存出现错误时自动重试。默认 1；留空表示不自动重试。": "Automatically retry when an image API call or image result save fails. Default is 1; leave empty to disable auto retry.",
  "图片结果重试次数": "Image result retry count",
  "保存策略": "Save policy",
  "填写 CPA 管理地址和访问密码，从远端同步图片账号号池。": "Enter the CPA admin URL and access password to sync the image account pool from the remote service.",
  "立即同步": "Sync now",
  "CPA 管理地址": "CPA admin URL",
  "访问密码": "Access password",
  "同步频率（分钟）": "Sync interval (minutes)",
  "信息": "Message",
  "实际预览": "Live preview",
  "基础信息": "Basic information",
  "站点访问设置": "Site access settings",
  "站点与插件 / MCP 授权": "Site and plugin / MCP authorization",
  "用于生成插件安装、MCP/OAuth 和分享链接。留空时根据当前请求自动识别。": "Used to generate plugin install, MCP/OAuth, and share links. Leave blank to detect it from the current request.",
  "站点访问设置加载中...": "Loading site access settings...",
  "站点访问设置加载失败": "Failed to load site access settings",
  "重新加载": "Reload",
  "公开访问地址": "Public access URL",
  "仅填写域名 origin，不要带 /install、查询参数或锚点。公网地址必须使用 HTTPS；本机和私有局域网地址可使用 HTTP。": "Enter the origin only, without /install, query parameters, or fragments. Public URLs must use HTTPS; localhost and private LAN URLs may use HTTP.",
  "当前生效地址": "Effective URL",
  "暂未识别": "Not detected yet",
  "环境变量 APP_PUBLIC_URL": "APP_PUBLIC_URL environment variable",
  "兼容环境变量 MALIANG_PUBLIC_BASE_URL": "Legacy MALIANG_PUBLIC_BASE_URL environment variable",
  "后台设置": "Admin setting",
  "自动检测": "Automatic detection",
  "环境变量正在优先生效": "An environment variable is taking precedence",
  "请在部署配置中修改公开访问地址；后台字段已锁定，避免保存不生效的重复配置。": "Change the public URL in the deployment configuration. The admin field is locked to prevent saving a duplicate setting that would not take effect.",
  "保存访问设置": "Save access settings",
  "站点访问设置已保存": "Site access settings saved",
  "站点访问设置保存失败": "Failed to save site access settings",
  "Remote MCP 授权": "Remote MCP authorization",
  "统一管理所有 Remote MCP 客户端的令牌有效期，不按 Codex、TRAE 等客户端名称区分。": "Manage token lifetimes for all Remote MCP clients without branching on client names such as Codex or TRAE.",
  "Remote MCP 授权设置加载中...": "Loading Remote MCP authorization settings...",
  "Remote MCP 授权设置加载失败": "Failed to load Remote MCP authorization settings",
  "插件 / MCP Access Token（天）": "Plugin / MCP Access Token (days)",
  "默认 7 天，可设置 1～365 天。所有 MCP 客户端统一使用。": "Defaults to 7 days and supports 1–365 days. The same value applies to every MCP client.",
  "插件 / MCP Refresh Token（天）": "Plugin / MCP Refresh Token (days)",
  "默认 90 天，可设置 30～3650 天；每次成功刷新都会重新计算有效期。": "Defaults to 90 days and supports 30–3650 days. Every successful refresh starts a new lifetime.",
  "仅向动态注册中声明 refresh_token 的客户端签发 Refresh Token。修改只影响之后新签发或刷新的令牌，现有令牌不会被强制改期。": "Refresh Tokens are issued only to clients that declare refresh_token during dynamic registration. Changes apply to newly issued or refreshed tokens and do not rewrite existing token expiry times.",
  "保存授权设置": "Save authorization settings",
  "Remote MCP 授权设置已保存": "Remote MCP authorization settings saved",
  "Remote MCP 授权设置保存失败": "Failed to save Remote MCP authorization settings",
  "默认 7 天，范围 1～365 天。": "Defaults to 7 days, with a range of 1–365 days.",
  "默认 90 天，范围 30～3650 天，刷新后滚动续期。": "Defaults to 90 days, with a range of 30–3650 days and rolling renewal after refresh.",
  "GitHub 入口": "GitHub entry",
  "GitHub 入口已开启": "GitHub entry enabled",
  "GitHub 入口已关闭": "GitHub entry disabled",
  "控制用户设置“关于”中的 GitHub 仓库入口；关闭后改用更新日志图标。": "Control the GitHub repository entry in user Settings > About. When disabled, the About navigation uses a changelog icon instead.",
  "AI 客户端安装入口": "AI client install entry",
  "AI 客户端安装入口已开启": "AI client install entry enabled",
  "AI 客户端安装入口已关闭": "AI client install entry disabled",
  "控制新对话空白页中的 AI 客户端推荐入口；关闭后不影响安装页直达地址。": "Control the AI client recommendation on the new-chat page. Disabling it does not affect direct install-page URLs.",
  "站点名称": "Site name",
  "保存品牌设置": "Save branding",
  "恢复默认": "Restore default",
  "用于工作台侧栏、配置中心和空白页品牌标识。建议上传透明 PNG 或 WebP。": "Used for the workbench sidebar, admin center, and blank-page branding. Transparent PNG or WebP is recommended.",
  "默认 Logo": "Default logo",
  "浏览器图标": "Browser icon",
  "用于浏览器标签页和收藏夹，可单独上传小尺寸图标。": "Used for browser tabs and bookmarks. A small icon can be uploaded separately.",
  "默认浏览器图标": "Default browser icon",
  "登录标题图": "Login title image",
  "登录页左侧品牌标题图，可分别设置浅色和暗色主题。": "Brand title image on the left side of the login page. Light and dark themes can be configured separately.",
  "默认浅色标题图": "Default light title image",
  "浅色标题": "Light title",
  "暗色标题": "Dark title",
  "默认暗色标题图": "Default dark title image",
  "浅色登录背景": "Light login background",
  "勾选多张后登录页自动轮播，可用箭头调整显示顺序。": "Select multiple images for login-page carousel. Use arrows to adjust the order.",
  "暗色登录背景": "Dark login background",
  "暗色主题下使用的登录背景池，默认保留当前暗色背景图。": "Background pool used in dark theme. The current dark background remains available by default.",
  "开启后使用“代理配置”中已启用的代理地址，适合 Gmail SMTP。": "When enabled, mail is sent through the enabled proxy in Proxy settings. Suitable for Gmail SMTP.",
  "SMTP 服务器": "SMTP server",
  "端口": "Port",
  "SMTP 账号": "SMTP account",
  "密码/授权码": "Password / authorization code",
  "发件人名称": "Sender name",
  "发件邮箱": "Sender email",
  "测试收件邮箱": "Test recipient email",
  "短信供应商": "SMS provider",
  "地域": "Region",
  "短信应用 ID": "SMS app ID",
  "短信签名": "SMS signature",
  "注册验证码模板 ID": "Registration code template ID",
  "找回密码模板 ID": "Password recovery template ID",
  "模板变量顺序": "Template parameter order",
  "按短信模板变量顺序填写。`code` 表示验证码，`minutes` 表示 10 分钟。": "Enter parameters in SMS template order. `code` is the verification code, and `minutes` means 10 minutes.",
  "测试手机号": "Test phone number",
  "每日备份时间": "Daily backup time",
  "保留天数": "Retention days",
  "备份目录": "Backup directory",
  "实际目录": "Actual directory",
  "立即备份": "Back up now",
  "代理地址": "Proxy URL",
  "重试次数": "Retry count",
  "保存代理配置": "Save proxy settings",
  "编辑调试文件": "Edit debug files",
  "保存 mask.png 和 request.json。": "Save mask.png and request.json.",
  "全部场景": "All scenarios",
  "尝试": "Attempts",
  "接口地址": "Endpoint URL",
  "时间/用户": "Time / user",
  "来源账号": "Source account",
  "结果": "Result",
  "配置审计": "Admin audit",
  "动作": "Action",
  "详情": "Details",
  "AI 每日文案": "AI daily copy",
  "API 模式": "API mode",
  "API 直连": "Direct API",
  "CPA 模式": "CPA mode",
  "ChatGPT 官网": "ChatGPT Web",
  "个团队": "teams",
  "个账号": "accounts",
  "不使用": "Do not use",
  "使用代理发送邮件": "Send email through proxy",
  "全部状态": "All statuses",
  "启用短信服务": "Enable SMS service",
  "启用邮件服务": "Enable email service",
  "在这里维护用户可见的版本记录。": "Maintain user-visible release notes here.",
  "成功：": "Success: ",
  "日期：": "Date: ",
  "最近备份": "Latest backup",
  "最近状态": "Latest status",
  "保存后会自动隐藏": "Hidden automatically after saving",
  "来源：": "Source: ",
  "状态：": "Status: ",
  "生成：": "Generated: ",
  "选择目录": "Select directory",
  "自动备份": "Automatic backup",
  "通常为邮箱账号": "Usually the email account",
  "隐藏 生成": "Hide generation",
  "隐藏 编辑": "Hide editing",
  "供应商配置": "Provider settings",
  "场景分配": "Scenario assignments",
  "模型配置分类": "Model configuration sections",
  "维护 OpenAI Chat Completions 兼容语言模型供应商；默认模型用于配置测试和未单独分配的场景。": "Maintain OpenAI Chat Completions-compatible providers. The default model is used for configuration tests and scenarios without an override.",
  "维护 OpenAI Chat Completions 兼容语言模型供应商；供应商默认模型用于配置测试，并作为场景分配的可选模型。": "Maintain OpenAI Chat Completions-compatible providers. Each provider's default model is used for configuration tests and is available for scenario assignments.",
  "为每个语言模型使用场景单独选择供应商和模型；未单独配置时跟随全局默认。": "Choose a provider and model for each language-model scenario. Scenarios without an override follow the global default.",
  "为每个语言模型使用场景选择模型；未单独配置时跟随全局默认。": "Choose a model for each language-model scenario. Scenarios without an override follow the global default.",
  "全局默认": "Global default",
  "来自排序最靠前的启用供应商及其默认模型。": "Uses the first enabled provider by sort order and its default model.",
  "未单独配置的场景会使用这里选择的模型。": "Scenarios without an override use the model selected here.",
  "跟随全局默认": "Follow global default",
  "推荐：": "Recommended: ",
  "跟随默认": "Following default",
  "已单独配置": "Overridden",
  "配置失效": "Invalid assignment",
  "运行时回退全局默认": "Falls back to the global default at runtime",
  "保存场景分配": "Save scenario assignments",
  "场景分配已保存": "Scenario assignments saved",
  "场景分配加载中...": "Loading scenario assignments...",
  "暂无启用的全局默认模型": "No enabled global default model",
  "暂无启用模型": "No enabled model",
  "也可手动填写模型": "Or enter a model manually",
  "创作增强": "Creative enhancement",
  "面向提示词创作、表单处理和图片续改的内容生成任务。": "Content-generation tasks for prompt creation, form processing, and image refinement.",
  "自动命名": "Automatic naming",
  "为用户和内容生成简短、易识别的名称。": "Generate short, recognizable names for users and content.",
  "内容理解": "Content understanding",
  "从管理员维护的候选分类中判断匹配项。": "Select matching items from the categories maintained by administrators.",
  "系统服务": "System services",
  "后台定时任务和生成前的治理能力。": "Scheduled background tasks and safeguards applied before generation.",
  "对话提示词优化": "Chat prompt optimization",
  "对话输入框里的 AI 提示词优化。": "Optimize AI prompts entered in the chat input.",
  "表单提示词优化": "Form prompt optimization",
  "站内表单和导出网页的 AI 优化。": "Optimize prompts in in-app forms and exported web pages.",
  "表单提示词翻译": "Form prompt translation",
  "站内表单和导出网页的中英翻译。": "Translate prompts between Chinese and English in in-app forms and exported web pages.",
  "图片续改建议": "Image edit suggestions",
  "图片完成前预生成及按需刷新的续改建议。": "Pre-generate follow-up edit suggestions before an image completes and refresh them on demand.",
  "对话标题": "Chat titles",
  "根据首条提示词生成对话标题。": "Generate a chat title from the first prompt.",
  "灵感标题": "Inspiration titles",
  "加入灵感空间时生成推荐标题。": "Generate a suggested title when adding an item to Inspiration.",
  "素材名称": "Asset names",
  "保存到素材库时生成素材名称。": "Generate an asset name when saving to the asset library.",
  "注册昵称": "Registration usernames",
  "为新注册用户生成昵称和候选昵称。": "Generate a username and alternatives for newly registered users.",
  "灵感风格判断": "Inspiration style classification",
  "自动选择最多三个灵感风格。": "Automatically select up to three Inspiration styles.",
  "素材标签判断": "Asset tag classification",
  "自动选择最多三个素材标签。": "Automatically select up to three asset tags.",
  "每日文案生成": "Daily copy generation",
  "每天生成空白页中文互动文案。": "Generate Chinese interactive copy for the blank page each day.",
  "每日文案翻译": "Daily copy translation",
  "生成或补齐空白页英文文案。": "Generate or complete the English copy for the blank page.",
  "在生图和图生图请求前审核提示词。": "Review prompts before text-to-image and image-to-image requests.",
  "质量优先": "Quality first",
  "速度优先": "Speed first",
  "低延迟优先": "Low latency first",
  "低成本优先": "Low cost first",
  "稳定输出优先": "Stable output first",
  "成本优先": "Cost first",
  "准确性优先": "Accuracy first",
  "昵称生成": "Username generation",
  "自动分类": "Automatic classification",
  "续改建议": "Edit suggestions",
  "默认模型": "Default model",
  "新增模型供应商": "Add model provider",
  "编辑模型供应商": "Edit model provider",
  "删除模型供应商": "Delete model provider",
  "启用模型供应商": "Enable model provider",
  "停用模型供应商": "Disable model provider"
};

const extraPersianConfigCopy: Record<string, string> = {
  "支持按账号、邮箱、手机号、团队和状态搜索筛选普通用户。": "کاربران عادی را بر اساس حساب، ایمیل، موبایل، تیم و وضعیت جستجو و فیلتر کنید.",
  "关闭后 C 端无法获取注册验证码或完成注册；后台新增账号不受影响。": "پس از خاموش شدن، کاربران سمت کاربر نمی‌توانند کد ثبت‌نام بگیرند یا ثبت‌نام را کامل کنند؛ حساب‌هایی که در مدیریت ساخته می‌شوند تحت تأثیر نیستند.",
  "搜索账号/用户名/邮箱/手机号": "جستجوی حساب / نام کاربری / ایمیل / موبایل",
  "新增账号": "افزودن حساب",
  "用户名": "نام کاربری",
  "账号": "حساب",
  "邮箱": "ایمیل",
  "手机号": "موبایل",
  "对话": "گفتگوها",
  "左侧按团队筛选账号，右侧维护账号与团队信息。": "در سمت چپ حساب‌ها را بر اساس تیم فیلتر کنید و در سمت راست اطلاعات حساب و تیم را مدیریت کنید.",
  "新增团队": "افزودن تیم",
  "全部分组": "همه گروه‌ها",
  "默认团队": "تیم پیش‌فرض",
  "团队名称": "نام تیم",
  "团队说明": "توضیح تیم",
  "用户主动申请共享后才会出现在这里；审核通过后才进入共享素材区。": "منابع پس از درخواست اشتراک توسط کاربر اینجا ظاهر می‌شوند و فقط پس از تأیید وارد بخش منابع مشترک می‌شوند.",
  "关闭后，新提交共享的素材会直接公开；历史待审素材仍保留当前状态。": "پس از خاموش شدن، منابع جدید مستقیماً منتشر می‌شوند؛ موارد قدیمی در انتظار بررسی با وضعیت فعلی باقی می‌مانند.",
  "素材审核状态": "وضعیت بررسی منابع",
  "搜索素材、用户、账号或标签": "جستجوی منبع، کاربر، حساب یا برچسب",
  "素材": "منبع",
  "提交用户": "ارسال‌کننده",
  "标签": "برچسب‌ها",
  "提交时间": "زمان ارسال",
  "审核时间": "زمان بررسی",
  "用户加入灵感空间后先进入审核；通过后才进入公共灵感空间。": "الهام‌های اضافه‌شده توسط کاربر ابتدا وارد بررسی می‌شوند و فقط پس از تأیید عمومی می‌شوند.",
  "关闭后，新加入灵感会直接公开；历史待审灵感仍保留当前状态。": "پس از خاموش شدن، الهام‌های جدید مستقیماً منتشر می‌شوند؛ موارد قدیمی در انتظار بررسی با وضعیت فعلی باقی می‌مانند.",
  "灵感审核状态": "وضعیت بررسی الهام",
  "搜索灵感、提示词、用户、账号或风格": "جستجوی الهام، پرامپت، کاربر، حساب یا سبک",
  "灵感": "الهام",
  "风格": "سبک",
  "空白页每日文案": "متن روزانه صفحه خالی",
  "开启后每天凌晨由启用的语言模型生成生图相关互动文案；关闭或失败时继续使用本地固定文案。": "پس از فعال شدن، هر بامداد مدل زبانی فعال متن‌های تعاملی مرتبط با تولید تصویر را می‌سازد؛ در حالت خاموش یا شکست، متن ثابت محلی استفاده می‌شود.",
  "生成数量": "تعداد تولید",
  "立即更新文案": "به‌روزرسانی فوری متن",
  "今日文案": "متن امروز",
  "真实记录存入配置数据库；静态 Markdown 文档由管理员自行维护，不参与系统读取。": "رکوردهای واقعی در پایگاه داده تنظیمات ذخیره می‌شوند؛ فایل Markdown ثابت توسط مدیر نگهداری می‌شود و سیستم آن را نمی‌خواند.",
  "新增日志": "افزودن گزارش",
  "账号管理": "مدیریت حساب‌ها",
  "维护图片账号号池、额度、优先级和同步状态。": "مخزن حساب‌های تصویر، سهمیه، اولویت و وضعیت همگام‌سازی را مدیریت کنید.",
  "全部刷新额度": "بازخوانی همه سهمیه‌ها",
  "批量导入": "ورود گروهی",
  "订阅套餐": "طرح اشتراک",
  "Codex 额度": "سهمیه Codex",
  "CPA统计": "آمار CPA",
  "本地统计": "آمار محلی",
  "认证信息": "اطلاعات احراز هویت",
  "优先级": "اولویت",
  "同步": "همگام‌سازی",
  "CPA、ChatGPT 官网和 API 直连统一按渠道维护。": "CPA، ChatGPT وب و API مستقیم همگی به صورت کانال مدیریت می‌شوند.",
  "调用策略": "راهبرد فراخوانی",
  "账号 / 地址": "حساب / آدرس",
  "独立维护 AI 优化提示词使用的 OpenAI Chat Completions 兼容语言模型，不复用图片渠道。": "مدل زبانی سازگار با OpenAI Chat Completions برای بهینه‌سازی پرامپت جداگانه مدیریت می‌شود و از کانال‌های تصویر استفاده نمی‌کند.",
  "新增供应商": "افزودن ارائه‌دهنده",
  "供应商": "ارائه‌دهنده",
  "地址": "آدرس",
  "参数": "پارامترها",
  "只审核对话里用户提交的生图/图生图提示词。关闭后不会调用审核模型，也不会拦截请求。": "فقط پرامپت‌های تولید تصویر و تصویر به تصویر ارسال‌شده توسط کاربر بررسی می‌شوند. پس از خاموش شدن، مدل بررسی فراخوانی نمی‌شود و درخواست‌ها مسدود نمی‌شوند.",
  "文本审核总开关": "کلید اصلی بررسی متن",
  "开启后在提交生图前审核用户提示词，命中拦截时不调用图片渠道。": "پس از فعال شدن، پرامپت کاربر پیش از تولید تصویر بررسی می‌شود؛ در صورت مسدود شدن، کانال تصویر فراخوانی نمی‌شود.",
  "审核异常策略": "سیاست خطای بررسی",
  "异常时放行": "اجازه در خطای بررسی",
  "异常时拦截": "مسدود در خطای بررسی",
  "拦截提示文案": "متن پیام مسدودسازی",
  "刷新记录": "بازخوانی رکوردها",
  "场景": "سناریو",
  "结论": "نتیجه",
  "风险": "ریسک",
  "提示词": "پرامپت",
  "原因": "دلیل",
  "模型/耗时": "مدل / زمان",
  "控制图片生成整体从哪类渠道选路。": "کنترل کنید تولید تصویر از کدام نوع کانال مسیر بگیرد.",
  "请求策略": "سیاست درخواست",
  "图片接口调用或图片结果保存出现错误时自动重试。默认 1；留空表示不自动重试。": "در صورت خطا در فراخوانی API تصویر یا ذخیره نتیجه، خودکار تلاش مجدد انجام می‌شود. پیش‌فرض 1 است؛ خالی یعنی بدون تلاش مجدد.",
  "图片结果重试次数": "تعداد تلاش مجدد نتیجه تصویر",
  "保存策略": "سیاست ذخیره",
  "填写 CPA 管理地址和访问密码，从远端同步图片账号号池。": "آدرس مدیریت CPA و رمز دسترسی را وارد کنید تا مخزن حساب‌های تصویر از راه دور همگام شود.",
  "立即同步": "همگام‌سازی فوری",
  "CPA 管理地址": "آدرس مدیریت CPA",
  "访问密码": "رمز دسترسی",
  "同步频率（分钟）": "فاصله همگام‌سازی (دقیقه)",
  "信息": "اطلاعات",
  "实际预览": "پیش‌نمایش واقعی",
  "基础信息": "اطلاعات پایه",
  "站点名称": "نام سایت",
  "保存品牌设置": "ذخیره برندسازی",
  "恢复默认": "بازگردانی پیش‌فرض",
  "用于工作台侧栏、配置中心和空白页品牌标识。建议上传透明 PNG 或 WebP。": "برای لوگوی نوار کناری، مرکز تنظیمات و صفحه خالی استفاده می‌شود. PNG یا WebP شفاف پیشنهاد می‌شود.",
  "默认 Logo": "لوگوی پیش‌فرض",
  "浏览器图标": "آیکن مرورگر",
  "用于浏览器标签页和收藏夹，可单独上传小尺寸图标。": "برای تب مرورگر و نشانک‌ها استفاده می‌شود و می‌توان آیکن کوچک جداگانه بارگذاری کرد.",
  "默认浏览器图标": "آیکن پیش‌فرض مرورگر",
  "登录标题图": "تصویر عنوان ورود",
  "登录页左侧品牌标题图，可分别设置浅色和暗色主题。": "تصویر عنوان برند در سمت چپ صفحه ورود؛ می‌توان برای تم روشن و تیره جداگانه تنظیم کرد.",
  "默认浅色标题图": "تصویر عنوان روشن پیش‌فرض",
  "浅色标题": "عنوان روشن",
  "暗色标题": "عنوان تیره",
  "默认暗色标题图": "تصویر عنوان تیره پیش‌فرض",
  "浅色登录背景": "پس‌زمینه ورود روشن",
  "勾选多张后登录页自动轮播，可用箭头调整显示顺序。": "با انتخاب چند تصویر، صفحه ورود به صورت چرخشی نمایش می‌دهد؛ با فلش‌ها ترتیب را تنظیم کنید.",
  "暗色登录背景": "پس‌زمینه ورود تیره",
  "暗色主题下使用的登录背景池，默认保留当前暗色背景图。": "مخزن پس‌زمینه ورود برای تم تیره؛ تصویر تیره فعلی به صورت پیش‌فرض حفظ می‌شود.",
  "开启后使用“代理配置”中已启用的代理地址，适合 Gmail SMTP。": "پس از فعال شدن، ایمیل از پروکسی فعال در تنظیمات پروکسی ارسال می‌شود؛ مناسب Gmail SMTP.",
  "SMTP 服务器": "سرور SMTP",
  "端口": "پورت",
  "SMTP 账号": "حساب SMTP",
  "密码/授权码": "رمز / کد مجوز",
  "发件人名称": "نام فرستنده",
  "发件邮箱": "ایمیل فرستنده",
  "测试收件邮箱": "ایمیل گیرنده تست",
  "短信供应商": "ارائه‌دهنده پیامک",
  "地域": "منطقه",
  "短信应用 ID": "شناسه برنامه پیامک",
  "短信签名": "امضای پیامک",
  "注册验证码模板 ID": "شناسه قالب کد ثبت‌نام",
  "模板变量顺序": "ترتیب متغیرهای قالب",
  "按短信模板变量顺序填写。`code` 表示验证码，`minutes` 表示 10 分钟。": "بر اساس ترتیب متغیرهای قالب پیامک وارد کنید. `code` یعنی کد تأیید و `minutes` یعنی ۱۰ دقیقه.",
  "测试手机号": "شماره تست",
  "每日备份时间": "زمان پشتیبان‌گیری روزانه",
  "保留天数": "روزهای نگهداری",
  "备份目录": "پوشه پشتیبان",
  "实际目录": "پوشه واقعی",
  "立即备份": "پشتیبان‌گیری فوری",
  "代理地址": "آدرس پروکسی",
  "重试次数": "تعداد تلاش مجدد",
  "保存代理配置": "ذخیره تنظیمات پروکسی",
  "编辑调试文件": "فایل‌های اشکال‌زدایی ویرایش",
  "保存 mask.png 和 request.json。": "mask.png و request.json ذخیره می‌شوند.",
  "全部场景": "همه سناریوها",
  "尝试": "تلاش‌ها",
  "接口地址": "آدرس Endpoint",
  "时间/用户": "زمان / کاربر",
  "来源账号": "حساب منبع",
  "结果": "نتیجه",
  "配置审计": "حسابرسی تنظیمات",
  "动作": "اقدام",
  "详情": "جزئیات",
  "AI 每日文案": "متن روزانه AI",
  "API 模式": "حالت API",
  "API 直连": "API مستقیم",
  "CPA 模式": "حالت CPA",
  "ChatGPT 官网": "ChatGPT وب",
  "个团队": "تیم",
  "个账号": "حساب",
  "不使用": "استفاده نشود",
  "上传 Logo": "بارگذاری لوگو",
  "上传图标": "بارگذاری آیکن",
  "上传标题图": "بارگذاری تصویر عنوان",
  "上传浅色背景": "بارگذاری پس‌زمینه روشن",
  "上传暗色背景": "بارگذاری پس‌زمینه تیره",
  "中国大陆 11 位手机号": "شماره ۱۱ رقمی چین",
  "使用代理发送邮件": "ارسال ایمیل از طریق پروکسی",
  "全部团队": "همه تیم‌ها",
  "全部用户": "همه کاربران",
  "全部状态": "همه وضعیت‌ها",
  "可用图片账号": "حساب‌های تصویر قابل استفاده",
  "只使用 CPA 额度代理渠道。": "فقط از کانال سهمیه CPA استفاده می‌شود.",
  "只使用 ChatGPT 官网逆向渠道，可配置官网额度、Codex 额度或都走。": "فقط از کانال معکوس ChatGPT وب استفاده می‌شود؛ سهمیه وب، Codex یا هر دو قابل تنظیم است.",
  "只使用 OpenAI 兼容或私有 API 直连渠道。": "فقط از OpenAI-compatible یا API خصوصی مستقیم استفاده می‌شود.",
  "启用 CPA 同步": "فعال کردن همگام‌سازی CPA",
  "启用短信服务": "فعال کردن سرویس پیامک",
  "启用自动备份": "فعال کردن پشتیبان‌گیری خودکار",
  "启用邮件服务": "فعال کردن سرویس ایمیل",
  "启用代理": "فعال کردن پروکسی",
  "启用用户": "کاربران فعال",
  "在这里维护用户可见的版本记录。": "اینجا رکوردهای نسخه قابل مشاهده برای کاربران را مدیریت کنید.",
  "备份运行数据库和图片素材文件；备份包包含敏感配置，请保存到可信目录。": "از پایگاه داده اجرا و فایل‌های تصویر پشتیبان بگیرید؛ بسته پشتیبان شامل تنظیمات حساس است، آن را در پوشه‌ای مطمئن نگه دارید.",
  "例如 http://127.0.0.1:8317": "مثلاً http://127.0.0.1:8317",
  "审核模型复用“模型配置”里排序最靠前的启用供应商；V1 只拦截模型返回 block 的提示词，review 仅记录。": "مدل بررسی از نخستین ارائه‌دهنده فعال در تنظیمات مدل استفاده می‌کند؛ در V1 فقط پرامپت‌هایی که مدل block برمی‌گرداند مسدود می‌شوند و review فقط ثبت می‌شود.",
  "已生成": "تولید شده",
  "开始日期": "تاریخ شروع",
  "结束日期": "تاریخ پایان",
  "成功：": "موفق: ",
  "找回密码模板 ID": "شناسه قالب بازیابی رمز",
  "按调用方式": "بر اساس روش فراخوانی",
  "按团队": "بر اساس تیم",
  "按渠道": "بر اساس کانال",
  "按渠道聚合": "تجمیع بر اساس کانال",
  "按用户": "بر اساس کاربر",
  "按账号聚合": "تجمیع بر اساس حساب",
  "按顺序依次尝试 CPA、ChatGPT 官网和 API 直连渠道。": "CPA، ChatGPT وب و API مستقیم به ترتیب امتحان می‌شوند.",
  "日期：": "تاریخ: ",
  "最近备份": "آخرین پشتیبان",
  "最近状态": "آخرین وضعیت",
  "最近登录": "آخرین ورود",
  "更新": "به‌روزرسانی",
  "来源：": "منبع: ",
  "模型": "مدل",
  "状态：": "وضعیت: ",
  "生成 / 编辑趋势": "روند تولید / ویرایش",
  "生成：": "تولید: ",
  "留空不重试": "خالی یعنی بدون تلاش مجدد",
  "留空则复用注册模板": "خالی باشد از قالب ثبت‌نام استفاده می‌شود",
  "当前使用": "در حال استفاده",
  "当前提示词可能存在安全风险，请调整后再试。": "پرامپت فعلی ممکن است ریسک ایمنی داشته باشد؛ لطفاً اصلاح کنید و دوباره تلاش کنید.",
  "移动出轮播": "حذف از چرخش",
  "移出轮播": "حذف از چرخش",
  "第 1 张": "تصویر 1",
  "第 2 张": "تصویر 2",
  "第 3 张": "تصویر 3",
  "第 4 张": "تصویر 4",
  "第 5 张": "تصویر 5",
  "第 6 张": "تصویر 6",
  "第 7 张": "تصویر 7",
  "第 8 张": "تصویر 8",
  "第 9 张": "تصویر 9",
  "第 10 张": "تصویر 10",
  "第 11 张": "تصویر 11",
  "第 12 张": "تصویر 12",
  "管理权限": "دسترسی مدیریت",
  "系统默认": "پیش‌فرض سیستم",
  "系统默认资源": "منبع پیش‌فرض سیستم",
  "统计分类": "دسته‌بندی آمار",
  "自动备份": "پشتیبان‌گیری خودکار",
  "自动模式": "حالت خودکار",
  "自助注册": "ثبت‌نام خودکار",
  "腾讯云访问密钥 SecretId": "کلید دسترسی Tencent Cloud SecretId",
  "设置为 Logo": "تنظیم به عنوان لوگو",
  "设为 Logo": "تنظیم به عنوان لوگو",
  "设为图标": "تنظیم به عنوان آیکن",
  "记录最近图片请求实际使用的渠道、调用方式、重试次数和接口地址。": "کانال واقعی، روش فراخوانی، تعداد تلاش مجدد و آدرس API درخواست‌های اخیر تصویر را ثبت می‌کند.",
  "记录语言模型调用的场景、供应商、状态、重试次数和接口地址；不保存请求正文和响应正文。": "سناریو، ارائه‌دهنده، وضعیت، تعداد تلاش مجدد و آدرس API فراخوانی مدل زبانی را ثبت می‌کند؛ متن درخواست و پاسخ ذخیره نمی‌شود.",
  "账号总数": "کل حساب‌ها",
  "账号池统计": "آمار مخزن حساب",
  "账号状态分布": "توزیع وضعیت حساب",
  "记录配置入口的重要操作。": "عملیات مهم مرکز تنظیمات را ثبت می‌کند.",
  "请求数": "تعداد درخواست‌ها",
  "配置全站统一的站点名称、Logo、登录页标题图和登录背景；系统默认资源会保留为可选项。": "نام سایت، لوگو، تصویر عنوان ورود و پس‌زمینه ورود را برای کل سایت تنظیم کنید؛ منابع پیش‌فرض سیستم همچنان قابل انتخاب می‌مانند.",
  "重命名资源": "تغییر نام منبع",
  "重试成功率": "نرخ موفقیت تلاش مجدد",
  "重试生成": "تولید مجدد",
  "重试请求": "درخواست‌های تکراری",
  "删除资源": "حذف منبع",
  "渠道失败排行": "رتبه‌بندی خطای کانال",
  "渠道数": "تعداد کانال‌ها",
  "渠道筛选": "فیلتر کانال",
  "渠道耗时排行": "رتبه‌بندی زمان کانال",
  "图片总数": "کل تصاویر",
  "图片数": "تعداد تصاویر",
  "图片趋势": "روند تصویر",
  "图片": "تصاویر",
  "团队": "تیم",
  "团队数": "تعداد تیم‌ها",
  "失败总数": "کل خطاها",
  "失败数": "تعداد خطا",
  "失败率": "نرخ خطا",
  "今日图片数": "تصاویر امروز",
  "用户图片数排行": "رتبه‌بندی تصاویر کاربران",
  "用户失败数排行": "رتبه‌بندی خطای کاربران",
  "用户数": "تعداد کاربران",
  "用户请求数排行": "رتبه‌بندی درخواست کاربران",
  "会话": "گفتگوها",
  "高频错误摘要": "خلاصه خطاهای پرتکرار",
  "禁用用户": "کاربران غیرفعال",
  "本地请求排行": "رتبه‌بندی درخواست محلی",
  "本地成功排行": "رتبه‌بندی موفقیت محلی",
  "本地失败排行": "رتبه‌بندی خطای محلی",
  "适合只消耗 Codex/CPA 额度。": "مناسب مصرف فقط سهمیه Codex/CPA.",
  "适合日常使用，某条链路失败后自动尝试下一条。": "مناسب استفاده روزانه؛ اگر یک مسیر شکست بخورد، مسیر بعدی خودکار امتحان می‌شود.",
  "适合标准 API Key 或第三方兼容接口。": "مناسب API Key استاندارد یا endpoint سازگار شخص ثالث.",
  "默认 Codex 优先，失败后可回退官网会话链路。": "پیش‌فرض Codex اولویت دارد و در صورت شکست می‌تواند به مسیر جلسه وب برگردد.",
  "审核通过的签名名称，不带【】": "نام امضای تأییدشده، بدون 【】",
  "用于 C 端手机号注册验证码和手机号找回密码验证码发送，当前支持腾讯云短信。": "برای ارسال کد ثبت‌نام موبایل و کد بازیابی رمز موبایل در سمت کاربر استفاده می‌شود؛ فعلاً Tencent Cloud SMS پشتیبانی می‌شود.",
  "用于 C 端邮箱注册验证码和找回密码验证码发送。": "برای ارسال کد ثبت‌نام ایمیل و کد بازیابی رمز عبور در سمت کاربر استفاده می‌شود.",
  "用于本地排查图片编辑问题，平时保持关闭。": "برای عیب‌یابی محلی ویرایش تصویر استفاده می‌شود؛ در حالت عادی خاموش بماند.",
  "用于测试 SMTP 是否可用，留空则发送到发件邮箱": "برای تست در دسترس بودن SMTP استفاده می‌شود؛ اگر خالی باشد به ایمیل فرستنده ارسال می‌شود.",
  "启用后，允许使用代理的请求会走该地址；代理请求失败时按重试次数自动重试。": "پس از فعال شدن، درخواست‌هایی که اجازه پروکسی دارند از این آدرس عبور می‌کنند؛ شکست پروکسی بر اساس تعداد تلاش مجدد تکرار می‌شود.",
  "发送测试短信": "ارسال پیامک تست",
  "发送测试邮件": "ارسال ایمیل تست",
  "创建时间": "زمان ایجاد",
  "今日暂未生成文案。": "متن امروز هنوز تولید نشده است.",
  "AI 生成": "تولید AI",
  "官网模式": "حالت وب",
  "开启": "روشن",
  "手动": "دستی",
  "新增渠道": "افزودن کانال",
  "保存后会自动隐藏": "پس از ذخیره خودکار پنهان می‌شود",
  "等待首次备份": "در انتظار نخستین پشتیبان",
  "选择目录": "انتخاب پوشه",
  "通常为邮箱账号": "معمولاً حساب ایمیل",
  "向前排序": "انتقال به جلو",
  "向后排序": "انتقال به عقب",
  "code 或 code,minutes": "code یا code,minutes",
  "隐藏 生成": "پنهان کردن تولید",
  "隐藏 编辑": "پنهان کردن ویرایش"
};

Object.assign(englishConfigCopy, extraEnglishConfigCopy);
Object.assign((localizedConfigCopy["fa-IR"] ??= {}), extraPersianConfigCopy);
(localizedPhraseReplacements["fa-IR"] ??= []).push(
  ["当前图标：", "آیکن فعلی: "],
  ["下次自动同步：", "همگام‌سازی خودکار بعدی: "],
  ["本次结果：", "نتیجه این بار: "],
  ["成功：", "موفق: "],
  ["重试تولید ", "تولید مجدد "],
  ["生成", "تولید"],
  ["编辑", "ویرایش"],
  ["秒", "ثانیه"],
  ["条启用渠道", " کانال فعال"],
  ["最近测试：", "آخرین تست: "]
);

const textNodeOriginals = new WeakMap<Text, string>();
const attributeOriginals = new WeakMap<Element, Map<string, string>>();
const allConfigCopyLocales: LocaleCode[] = ["zh-CN", "zh-TW", "en-US", ...configCopyLocales];
const TRANSLATABLE_ATTRIBUTES = ["aria-label", "placeholder", "title"] as const;
const SKIP_ATTRIBUTE_SELECTOR = [
  "[data-config-no-translate]",
  ".markdown-body",
  ".review-prompt-card",
  ".review-prompt-modal-body",
  "pre",
  "code"
].join(",");
const SKIP_TEXT_SELECTOR = [
  "script",
  "style",
  "textarea",
  "input",
  "select",
  "option",
  "pre",
  "code",
  "tbody",
  "[contenteditable='true']",
  "[data-config-no-translate]",
  ".markdown-body",
  ".review-prompt-card",
  ".review-prompt-modal-body"
].join(",");

function preserveWhitespace(source: string, translated: string) {
  const leading = source.match(/^\s*/)?.[0] ?? "";
  const trailing = source.match(/\s*$/)?.[0] ?? "";
  return `${leading}${translated}${trailing}`;
}

function isKnownTranslatedValue(original: string, current: string) {
  const normalizedCurrent = current.trim();
  if (!normalizedCurrent) return false;
  return allConfigCopyLocales.some((locale) => translateConfigCopy(original.trim(), locale).trim() === normalizedCurrent);
}

export function translateConfigCopy(source: string, locale: LocaleCode) {
  if (!source || locale === "zh-CN") return source;
  if (locale === "zh-TW") return toTraditionalChinese(source);
  const trimmed = source.trim();
  if (locale === "en-US") {
    const exact = englishConfigCopy[trimmed];
    if (exact) return exact;
  } else {
    const localizedExact = localizedConfigCopy[locale as ConfigCopyLocale]?.[trimmed];
    if (localizedExact) return localizedExact;
    const englishFallback = englishConfigCopy[trimmed];
    if (englishFallback) return englishFallback;
  }
  let translated = trimmed;
  const phraseReplacements = locale === "en-US" ? englishPhraseReplacements : localizedPhraseReplacements[locale as ConfigCopyLocale] ?? [];
  for (const [from, to] of phraseReplacements) {
    translated = translated.split(from).join(to);
  }
  return translated === trimmed ? source : translated;
}

export function useConfigCopy() {
  const { resolvedLanguage } = useI18n();
  return useCallback((source: string) => translateConfigCopy(source, resolvedLanguage), [resolvedLanguage]);
}

function originalAttributeValue(element: Element, attribute: string, current: string, locale: LocaleCode) {
  let originals = attributeOriginals.get(element);
  if (!originals) {
    originals = new Map();
    attributeOriginals.set(element, originals);
  }
  const stored = originals.get(attribute);
  if (!stored) {
    originals.set(attribute, current);
    return current;
  }
  const translatedStored = translateConfigCopy(stored, locale);
  if (current !== translatedStored && !isKnownTranslatedValue(stored, current)) {
    originals.set(attribute, current);
    return current;
  }
  return stored;
}

function translateTextNode(node: Text, locale: LocaleCode) {
  const parent = node.parentElement;
  if (!parent || parent.closest(SKIP_TEXT_SELECTOR)) return;
  const current = node.nodeValue ?? "";
  const trimmed = current.trim();
  if (!trimmed) return;
  const stored = textNodeOriginals.get(node);
  let original = stored ?? current;
  const translatedStored = preserveWhitespace(original, translateConfigCopy(original.trim(), locale));
  if (stored && current !== translatedStored && !isKnownTranslatedValue(original, current)) {
    original = current;
    textNodeOriginals.set(node, original);
  } else if (!stored) {
    textNodeOriginals.set(node, original);
  }
  const translated = preserveWhitespace(original, translateConfigCopy(original.trim(), locale));
  if (node.nodeValue !== translated) node.nodeValue = translated;
}

function translateElementAttributes(root: HTMLElement, locale: LocaleCode) {
  const selector = TRANSLATABLE_ATTRIBUTES.map((attribute) => `[${attribute}]`).join(",");
  const elements = [root, ...Array.from(root.querySelectorAll(selector))];
  for (const element of elements) {
    if (element.closest(SKIP_ATTRIBUTE_SELECTOR)) continue;
    for (const attribute of TRANSLATABLE_ATTRIBUTES) {
      const current = element.getAttribute(attribute);
      if (!current?.trim()) continue;
      const original = originalAttributeValue(element, attribute, current, locale);
      const translated = translateConfigCopy(original.trim(), locale);
      if (translated !== current) element.setAttribute(attribute, translated);
    }
  }
}

function translateElementText(root: HTMLElement, locale: LocaleCode) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode();
  while (node) {
    translateTextNode(node as Text, locale);
    node = walker.nextNode();
  }
}

function translateConfigScope(root: HTMLElement, locale: LocaleCode) {
  translateElementText(root, locale);
  translateElementAttributes(root, locale);
}

export function useConfigCopyScope(rootRef: RefObject<HTMLElement | null>) {
  const { resolvedLanguage } = useI18n();
  const pendingFrameRef = useRef<number | null>(null);

  useEffect(() => {
    const root = rootRef.current;
    if (!root || typeof document === "undefined") return;

    const schedule = () => {
      if (pendingFrameRef.current !== null) window.cancelAnimationFrame(pendingFrameRef.current);
      pendingFrameRef.current = window.requestAnimationFrame(() => {
        pendingFrameRef.current = null;
        translateConfigScope(root, resolvedLanguage);
      });
    };

    schedule();
    const observer = new MutationObserver(schedule);
    observer.observe(root, {
      childList: true,
      subtree: true
    });

    return () => {
      observer.disconnect();
      if (pendingFrameRef.current !== null) {
        window.cancelAnimationFrame(pendingFrameRef.current);
        pendingFrameRef.current = null;
      }
    };
  }, [resolvedLanguage, rootRef]);
}
